import type { FillBlankQuestion } from "../bibleQuiz";
import { getDifficulty, questionId } from "./shared";

type FillBlankItem = {
  category: string;
  clue: string;
  answer: string;
  accepted?: string[];
  explanation: string;
  reference: string;
};

const levelData: Record<number, FillBlankItem[]> = {
  1: [
    {
      category: "창조",
      clue: "하나님이 천지를 창조하신 기간(날 수)",
      answer: "엿새",
      accepted: ["6일", "육일", "여섯 날"],
      explanation: "하나님은 엿새 동안 천지 만물을 창조하시고 일곱째 날에 안식하셨다.",
      reference: "창세기 1:31-2:2",
    },
    {
      category: "인물",
      clue: "최초의 사람이며 아담의 아내가 된 여자",
      answer: "하와",
      accepted: ["이브"],
      explanation: "하나님은 아담의 갈빗대로 하와를 만드셨고 그녀는 모든 산 자의 어미가 되었다.",
      reference: "창세기 3:20",
    },
    {
      category: "장소",
      clue: "아담과 하와가 처음 살았던 동산",
      answer: "에덴동산",
      accepted: ["에덴 동산", "에덴"],
      explanation: "하나님은 동방의 에덴에 동산을 창설하시고 사람을 그곳에 두셨다.",
      reference: "창세기 2:8",
    },
    {
      category: "사건",
      clue: "노아가 홍수를 피하기 위해 만든 배",
      answer: "방주",
      accepted: ["노아의 방주"],
      explanation: "노아는 하나님의 명령대로 고페르 나무로 방주를 만들어 가족과 동물을 구원했다.",
      reference: "창세기 6:14",
    },
    {
      category: "사건",
      clue: "사람들이 하늘에 닿으려고 쌓다가 언어가 혼잡해진 탑",
      answer: "바벨탑",
      accepted: ["바벨 탑", "바벨"],
      explanation: "사람들이 바벨탑을 쌓자 하나님이 언어를 혼잡하게 하여 온 지면에 흩으셨다.",
      reference: "창세기 11:9",
    },
    {
      category: "인물",
      clue: "믿음의 조상으로 갈대아 우르에서 부름받은 족장",
      answer: "아브라함",
      accepted: ["아브람"],
      explanation: "하나님은 아브라함을 부르사 큰 민족을 이루는 복의 근원이 되게 하셨다.",
      reference: "창세기 12:2",
    },
    {
      category: "인물",
      clue: "아브라함과 사라가 노년에 낳은 약속의 아들",
      answer: "이삭",
      explanation: "하나님의 약속대로 사라는 노년에 이삭을 낳았고 이삭은 언약의 후사가 되었다.",
      reference: "창세기 21:3",
    },
    {
      category: "인물",
      clue: "에서의 동생이며 후에 이스라엘로 이름이 바뀐 족장",
      answer: "야곱",
      explanation: "야곱은 얍복강에서 하나님과 씨름한 후 이스라엘이라는 이름을 받았다.",
      reference: "창세기 32:28",
    },
    {
      category: "인물",
      clue: "형들에게 팔려 애굽의 총리가 된 야곱의 아들",
      answer: "요셉",
      explanation: "요셉은 형들에게 팔려 애굽에 갔으나 총리가 되어 가족을 기근에서 구원했다.",
      reference: "창세기 41:41",
    },
    {
      category: "사건",
      clue: "하나님이 소돔과 함께 유황불로 멸하신 또 다른 죄악의 성",
      answer: "고모라",
      explanation: "하나님은 죄악이 가득한 소돔과 고모라를 하늘에서 내린 유황불로 멸하셨다.",
      reference: "창세기 19:24",
    },
  ],
  2: [
    {
      category: "인물",
      clue: "이스라엘 백성을 애굽에서 인도해 낸 지도자",
      answer: "모세",
      explanation: "하나님은 모세를 세워 이스라엘 백성을 애굽의 종살이에서 인도해 내셨다.",
      reference: "출애굽기 3:10",
    },
    {
      category: "사건",
      clue: "모세가 처음 하나님을 만난 떨기나무의 모습",
      answer: "불타는 떨기나무",
      accepted: ["불붙은 떨기나무", "떨기나무"],
      explanation: "호렙 산에서 불이 붙었으나 사라지지 않는 떨기나무 가운데서 하나님이 모세를 부르셨다.",
      reference: "출애굽기 3:2",
    },
    {
      category: "사건",
      clue: "애굽에 내린 열 가지 재앙 중 마지막 재앙",
      answer: "장자의 죽음",
      accepted: ["처음 난 것의 죽음", "장자 재앙"],
      explanation: "마지막 재앙으로 애굽의 모든 처음 난 것이 죽었으나 이스라엘은 유월절 어린양의 피로 보호받았다.",
      reference: "출애굽기 12:29",
    },
    {
      category: "절기",
      clue: "어린양의 피로 죽음을 넘긴 것을 기념하는 절기",
      answer: "유월절",
      explanation: "이스라엘은 문설주에 바른 어린양의 피로 죽음의 재앙을 넘겼고 이를 유월절로 지킨다.",
      reference: "출애굽기 12:13",
    },
    {
      category: "사건",
      clue: "이스라엘이 마른 땅으로 건넌 갈라진 바다",
      answer: "홍해",
      explanation: "하나님은 홍해를 갈라 이스라엘이 마른 땅으로 건너게 하시고 애굽 군대를 수장시키셨다.",
      reference: "출애굽기 14:21",
    },
    {
      category: "장소",
      clue: "모세가 십계명을 받은 산",
      answer: "시내산",
      accepted: ["시내 산", "시나이산"],
      explanation: "하나님은 시내산에서 모세에게 십계명을 비롯한 율법을 주셨다.",
      reference: "출애굽기 19:20",
    },
    {
      category: "양식",
      clue: "광야에서 이스라엘에게 매일 내린 하늘의 양식",
      answer: "만나",
      explanation: "하나님은 광야에서 매일 아침 만나를 내려 이스라엘 백성을 먹이셨다.",
      reference: "출애굽기 16:15",
    },
    {
      category: "물건",
      clue: "십계명 돌판을 넣어 둔 거룩한 궤",
      answer: "언약궤",
      accepted: ["법궤", "증거궤"],
      explanation: "언약궤 안에는 두 돌판이 들어 있었고 그 위 속죄소에서 하나님이 임재하셨다.",
      reference: "출애굽기 25:16",
    },
    {
      category: "인물",
      clue: "모세의 형이며 이스라엘의 첫 대제사장",
      answer: "아론",
      explanation: "아론은 모세의 대변자이자 이스라엘의 첫 대제사장으로 세워졌다.",
      reference: "출애굽기 28:1",
    },
    {
      category: "사건",
      clue: "모세가 시내산에 있을 때 백성이 만든 우상",
      answer: "금송아지",
      accepted: ["금 송아지"],
      explanation: "백성은 모세가 산에 머무는 동안 아론에게 금송아지를 만들게 하여 우상으로 섬겼다.",
      reference: "출애굽기 32:4",
    },
  ],
  3: [
    {
      category: "인물",
      clue: "다윗이 물맷돌로 쓰러뜨린 블레셋 거인",
      answer: "골리앗",
      explanation: "소년 다윗은 물매와 돌 하나로 블레셋의 거인 골리앗을 쓰러뜨렸다.",
      reference: "사무엘상 17:49",
    },
    {
      category: "인물",
      clue: "다윗에게 기름 부어 왕으로 세운 선지자",
      answer: "사무엘",
      explanation: "선지자 사무엘은 베들레헴에서 이새의 아들 다윗에게 기름을 부어 왕으로 세웠다.",
      reference: "사무엘상 16:13",
    },
    {
      category: "인물",
      clue: "다윗을 시기하여 죽이려 한 이스라엘의 첫 왕",
      answer: "사울",
      explanation: "이스라엘의 첫 왕 사울은 다윗의 명성을 시기하여 그를 죽이려 했다.",
      reference: "사무엘상 18:9",
    },
    {
      category: "인물",
      clue: "다윗과 깊은 우정을 나눈 사울의 아들",
      answer: "요나단",
      explanation: "사울의 아들 요나단은 다윗과 언약을 맺고 자기 생명같이 그를 사랑했다.",
      reference: "사무엘상 18:1",
    },
    {
      category: "인물",
      clue: "다윗이 범죄한 후 결혼하여 솔로몬을 낳은 여인",
      answer: "밧세바",
      explanation: "다윗은 밧세바와 범죄한 후 회개했고 그녀에게서 솔로몬이 태어났다.",
      reference: "사무엘하 12:24",
    },
    {
      category: "인물",
      clue: "다윗의 죄를 책망한 선지자",
      answer: "나단",
      explanation: "선지자 나단은 비유로 다윗의 죄를 지적하여 그를 회개하게 했다.",
      reference: "사무엘하 12:7",
    },
    {
      category: "인물",
      clue: "다윗의 뒤를 이어 왕이 된 지혜로운 아들",
      answer: "솔로몬",
      explanation: "다윗의 아들 솔로몬은 하나님께 지혜를 구하여 이스라엘을 다스렸다.",
      reference: "열왕기상 3:12",
    },
    {
      category: "건축",
      clue: "솔로몬이 예루살렘에 건축한 하나님의 집",
      answer: "성전",
      accepted: ["예루살렘 성전", "여호와의 성전"],
      explanation: "솔로몬은 예루살렘에 여호와의 성전을 건축하여 언약궤를 안치했다.",
      reference: "열왕기상 6:14",
    },
    {
      category: "사건",
      clue: "솔로몬을 시험하러 찾아온 먼 나라의 여왕",
      answer: "스바 여왕",
      accepted: ["스바의 여왕", "시바 여왕"],
      explanation: "스바 여왕은 솔로몬의 지혜를 시험하러 찾아왔다가 그 지혜와 영광에 감탄했다.",
      reference: "열왕기상 10:1",
    },
    {
      category: "장소",
      clue: "다윗이 점령하여 이스라엘의 수도로 삼은 성",
      answer: "예루살렘",
      accepted: ["시온성", "시온"],
      explanation: "다윗은 여부스 사람의 성 시온을 점령하여 다윗 성, 곧 예루살렘을 수도로 삼았다.",
      reference: "사무엘하 5:7",
    },
  ],
  4: [
    {
      category: "장소",
      clue: "예수님이 태어나신 유대 베들레헴의 장소",
      answer: "마구간",
      accepted: ["구유", "베들레헴 마구간"],
      explanation: "여관에 방이 없어 예수님은 베들레헴 마구간에서 나시고 구유에 뉘셨다.",
      reference: "누가복음 2:7",
    },
    {
      category: "인물",
      clue: "예수님을 잉태하여 낳은 동정녀 어머니",
      answer: "마리아",
      explanation: "천사 가브리엘의 수태고지대로 동정녀 마리아가 성령으로 예수님을 잉태했다.",
      reference: "누가복음 1:31",
    },
    {
      category: "인물",
      clue: "요단강에서 예수님께 세례를 준 선지자",
      answer: "세례 요한",
      accepted: ["요한", "침례 요한"],
      explanation: "세례 요한은 요단강에서 예수님께 세례를 주었고 그때 성령이 비둘기같이 임했다.",
      reference: "마태복음 3:13",
    },
    {
      category: "사건",
      clue: "예수님이 광야에서 사십 일 동안 받으신 것",
      answer: "시험",
      accepted: ["마귀의 시험", "유혹"],
      explanation: "예수님은 광야에서 사십 일을 금식하신 후 마귀에게 세 가지 시험을 받고 이기셨다.",
      reference: "마태복음 4:1",
    },
    {
      category: "지명",
      clue: "예수님이 자라나신 갈릴리의 동네",
      answer: "나사렛",
      explanation: "예수님은 갈릴리 나사렛에서 자라나셨기에 나사렛 예수라 불리셨다.",
      reference: "누가복음 2:39-40",
    },
    {
      category: "수",
      clue: "예수님이 세우신 핵심 제자의 수",
      answer: "열두 명",
      accepted: ["12명", "열둘", "열두 제자"],
      explanation: "예수님은 열두 제자를 사도로 세워 함께 다니며 복음을 전하게 하셨다.",
      reference: "마가복음 3:14",
    },
    {
      category: "인물",
      clue: "예수님을 은 삼십에 판 가룟 출신 제자",
      answer: "가룟 유다",
      accepted: ["유다"],
      explanation: "가룟 유다는 은 삼십에 예수님을 대제사장들에게 팔아넘겼다.",
      reference: "마태복음 26:15",
    },
    {
      category: "장소",
      clue: "예수님이 십자가에 못 박히신 해골이라는 곳",
      answer: "골고다",
      accepted: ["갈보리"],
      explanation: "예수님은 해골의 곳이라 하는 골고다에서 십자가에 못 박히셨다.",
      reference: "마태복음 27:33",
    },
    {
      category: "사건",
      clue: "십자가에 죽으신 예수님이 사흘 만에 일어나신 사건",
      answer: "부활",
      accepted: ["다시 살아나심"],
      explanation: "예수님은 죽으신 지 사흘 만에 무덤에서 부활하사 죽음을 이기셨다.",
      reference: "마가복음 16:6",
    },
    {
      category: "사건",
      clue: "부활하신 예수님이 제자들 앞에서 하늘로 올라가신 일",
      answer: "승천",
      explanation: "예수님은 부활 후 제자들이 보는 가운데 하늘로 올려져 가셨다.",
      reference: "사도행전 1:9",
    },
  ],
  5: [
    {
      category: "비유",
      clue: "강도 만난 사람을 도와준 비유 속 이방인",
      answer: "선한 사마리아인",
      accepted: ["사마리아인"],
      explanation: "예수님은 강도 만난 자를 돌본 사마리아인의 비유로 참된 이웃 사랑을 가르치셨다.",
      reference: "누가복음 10:33",
    },
    {
      category: "비유",
      clue: "재산을 탕진하고 돌아온 작은 아들의 비유 제목",
      answer: "탕자",
      accepted: ["탕자의 비유", "잃은 아들"],
      explanation: "탕자의 비유는 회개하고 돌아온 죄인을 기쁘게 맞이하시는 아버지의 사랑을 보여 준다.",
      reference: "누가복음 15:20",
    },
    {
      category: "기적",
      clue: "예수님이 가나 혼인 잔치에서 물로 만드신 것",
      answer: "포도주",
      explanation: "예수님은 가나의 혼인 잔치에서 물을 포도주로 변하게 하신 첫 표적을 행하셨다.",
      reference: "요한복음 2:9",
    },
    {
      category: "기적",
      clue: "오천 명을 먹이신 기적에 사용된 떡과 물고기",
      answer: "오병이어",
      accepted: ["떡 다섯 개와 물고기 두 마리", "보리떡 다섯 개"],
      explanation: "예수님은 떡 다섯 개와 물고기 두 마리로 오천 명을 먹이고도 남게 하셨다.",
      reference: "요한복음 6:9-11",
    },
    {
      category: "기적",
      clue: "예수님이 풍랑 이는 갈릴리 호수 위에서 하신 일",
      answer: "물 위를 걸으심",
      accepted: ["물 위로 걸으심", "바다 위를 걸으심"],
      explanation: "예수님은 바람이 거센 갈릴리 바다 위를 걸어 제자들에게 오셨다.",
      reference: "마태복음 14:25",
    },
    {
      category: "기적",
      clue: "예수님이 죽은 지 나흘 만에 살리신 베다니 사람",
      answer: "나사로",
      explanation: "예수님은 무덤에 있은 지 나흘 된 나사로를 불러내어 다시 살리셨다.",
      reference: "요한복음 11:43-44",
    },
    {
      category: "비유",
      clue: "씨가 길가, 돌밭, 가시밭, 좋은 땅에 떨어진 비유",
      answer: "씨 뿌리는 자",
      accepted: ["씨 뿌리는 자의 비유", "씨 뿌리는 비유"],
      explanation: "씨 뿌리는 자의 비유는 말씀을 받는 사람의 네 가지 마음 밭을 가르친다.",
      reference: "마태복음 13:3-8",
    },
    {
      category: "비유",
      clue: "백 마리 중 한 마리를 찾아 나선 목자의 비유 대상",
      answer: "잃은 양",
      accepted: ["잃은 양 한 마리", "잃어버린 양"],
      explanation: "잃은 양의 비유는 죄인 한 사람의 회개를 기뻐하시는 하나님의 마음을 보여 준다.",
      reference: "누가복음 15:4",
    },
    {
      category: "기적",
      clue: "예수님이 진흙을 발라 눈을 뜨게 하신 사람의 상태",
      answer: "맹인",
      accepted: ["소경", "날 때부터 맹인", "시각장애인"],
      explanation: "예수님은 날 때부터 맹인 된 자의 눈에 진흙을 발라 실로암에서 씻게 하여 보게 하셨다.",
      reference: "요한복음 9:6-7",
    },
    {
      category: "비유",
      clue: "주인이 종들에게 맡긴 재능을 뜻하는 비유 속 화폐",
      answer: "달란트",
      accepted: ["달란트 비유"],
      explanation: "달란트 비유는 맡겨진 것을 충성되게 사용해야 함을 가르친다.",
      reference: "마태복음 25:15",
    },
  ],
  6: [
    {
      category: "사건",
      clue: "오순절에 제자들에게 임하여 방언을 말하게 한 분",
      answer: "성령",
      explanation: "오순절에 성령이 불의 혀같이 임하여 제자들이 여러 언어로 말하게 되었다.",
      reference: "사도행전 2:4",
    },
    {
      category: "인물",
      clue: "오순절 설교를 한 후 초대교회를 이끈 수제자",
      answer: "베드로",
      explanation: "베드로는 오순절에 담대히 설교하여 삼천 명이 회개하게 한 초대교회 지도자였다.",
      reference: "사도행전 2:14",
    },
    {
      category: "인물",
      clue: "교회의 첫 순교자가 된 일곱 집사 중 한 사람",
      answer: "스데반",
      explanation: "스데반은 복음을 증거하다 돌에 맞아 교회의 첫 순교자가 되었다.",
      reference: "사도행전 7:59-60",
    },
    {
      category: "인물",
      clue: "다메섹 도상에서 회심하여 이방인의 사도가 된 사람",
      answer: "바울",
      accepted: ["사울"],
      explanation: "교회를 핍박하던 사울은 다메섹 도상에서 예수님을 만나 이방인의 사도 바울이 되었다.",
      reference: "사도행전 9:3-6",
    },
    {
      category: "장소",
      clue: "제자들이 처음으로 그리스도인이라 불린 도시",
      answer: "안디옥",
      explanation: "안디옥 교회에서 제자들이 비로소 그리스도인이라 일컬음을 받았다.",
      reference: "사도행전 11:26",
    },
    {
      category: "인물",
      clue: "베드로의 전도로 세례받은 로마 백부장",
      answer: "고넬료",
      explanation: "이방인 백부장 고넬료가 베드로의 전도로 성령을 받고 세례를 받았다.",
      reference: "사도행전 10:44-48",
    },
    {
      category: "인물",
      clue: "바울의 1차 전도 여행에 동행한 위로의 아들",
      answer: "바나바",
      explanation: "바나바는 바울을 안디옥 교회에 천거하고 1차 전도 여행에 함께한 동역자였다.",
      reference: "사도행전 13:2",
    },
    {
      category: "사건",
      clue: "바울과 실라가 옥에 갇혔을 때 옥문을 연 자연 현상",
      answer: "지진",
      explanation: "빌립보 감옥에서 바울과 실라가 찬송할 때 큰 지진이 나 옥문이 열렸다.",
      reference: "사도행전 16:26",
    },
    {
      category: "인물",
      clue: "두아디라 출신으로 빌립보에서 회심한 자색 옷감 장수",
      answer: "루디아",
      explanation: "자색 옷감 장사 루디아는 빌립보에서 바울의 말을 듣고 온 가족이 세례를 받았다.",
      reference: "사도행전 16:14-15",
    },
    {
      category: "장소",
      clue: "바울이 알지 못하는 신의 단을 보고 복음을 전한 곳",
      answer: "아덴",
      accepted: ["아테네", "아레오바고"],
      explanation: "바울은 아덴의 아레오바고에서 알지 못하는 신의 단을 인용하며 복음을 전했다.",
      reference: "사도행전 17:22-23",
    },
  ],
  7: [
    {
      category: "선지자",
      clue: "큰 물고기 배 속에서 삼 일을 지낸 선지자",
      answer: "요나",
      explanation: "요나는 니느웨로 가라는 명령을 피하다가 큰 물고기 배 속에서 삼 일을 지냈다.",
      reference: "요나 1:17",
    },
    {
      category: "지명",
      clue: "요나가 회개를 외쳐 멸망을 면한 앗수르의 큰 성",
      answer: "니느웨",
      explanation: "니느웨 성은 요나의 외침에 온 성이 회개하여 멸망을 면했다.",
      reference: "요나 3:5",
    },
    {
      category: "구절",
      clue: "미가가 예언한 메시아의 탄생지",
      answer: "베들레헴",
      accepted: ["베들레헴 에브라다"],
      explanation: "미가는 베들레헴 에브라다에서 이스라엘을 다스릴 자가 나오리라 예언했다.",
      reference: "미가 5:2",
    },
    {
      category: "구절",
      clue: "요엘이 예언한, 만민에게 부어질 하나님의 영",
      answer: "성령",
      accepted: ["영", "내 영"],
      explanation: "요엘은 하나님이 모든 육체에게 그의 영을 부어 주실 것을 예언했다.",
      reference: "요엘 2:28",
    },
    {
      category: "선지자",
      clue: "음란한 여인 고멜과 결혼한 사랑의 선지자",
      answer: "호세아",
      explanation: "호세아는 음란한 아내 고멜과의 결혼으로 배역한 이스라엘을 향한 하나님의 사랑을 보였다.",
      reference: "호세아 1:2-3",
    },
    {
      category: "선지자",
      clue: "공의를 물같이 흐르게 하라고 외친 목자 출신 선지자",
      answer: "아모스",
      explanation: "드고아의 목자 아모스는 정의를 물같이, 공의를 마르지 않는 강같이 흐르게 하라고 외쳤다.",
      reference: "아모스 5:24",
    },
    {
      category: "선지자",
      clue: "여호와의 날과 메뚜기 재앙을 예언한 선지자",
      answer: "요엘",
      explanation: "요엘은 메뚜기 재앙을 통해 여호와의 날과 회개를 촉구했다.",
      reference: "요엘 1:4",
    },
    {
      category: "선지자",
      clue: "에돔의 멸망을 예언한, 가장 짧은 책의 선지자",
      answer: "오바댜",
      explanation: "오바댜는 한 장으로 된 가장 짧은 예언서로 에돔의 교만과 멸망을 선포했다.",
      reference: "오바댜 1:4",
    },
    {
      category: "구절",
      clue: "스가랴가 예언한, 나귀 새끼를 타고 오시는 분",
      answer: "왕",
      accepted: ["메시아", "시온의 왕"],
      explanation: "스가랴는 겸손하여 나귀 새끼를 타고 오는 시온의 왕을 예언했다.",
      reference: "스가랴 9:9",
    },
    {
      category: "구절",
      clue: "말라기가 책망한, 백성이 하나님의 것을 도둑질한 것",
      answer: "십일조",
      accepted: ["십일조와 봉헌물"],
      explanation: "말라기는 백성이 십일조와 봉헌물로 하나님의 것을 도둑질했다고 책망했다.",
      reference: "말라기 3:8",
    },
  ],
  8: [
    {
      category: "인물",
      clue: "모세를 이어 이스라엘을 가나안으로 인도한 지도자",
      answer: "여호수아",
      explanation: "여호수아는 모세의 뒤를 이어 이스라엘을 이끌고 요단강을 건너 가나안에 들어갔다.",
      reference: "여호수아 1:2",
    },
    {
      category: "사건",
      clue: "이스라엘이 칠 일 동안 돌자 무너진 성",
      answer: "여리고",
      accepted: ["여리고성"],
      explanation: "이스라엘이 언약궤를 메고 여리고 성을 칠 일째 일곱 바퀴 돌며 외치자 성벽이 무너졌다.",
      reference: "여호수아 6:20",
    },
    {
      category: "인물",
      clue: "삼손에게 힘의 비밀을 알아내어 배신한 여인",
      answer: "들릴라",
      explanation: "블레셋의 사주를 받은 들릴라는 삼손의 머리카락에 있는 힘의 비밀을 알아내 배신했다.",
      reference: "사사기 16:18-19",
    },
    {
      category: "인물",
      clue: "삼백 명으로 미디안을 물리친 사사",
      answer: "기드온",
      explanation: "기드온은 삼백 명의 용사로 횃불과 나팔을 사용해 미디안 대군을 물리쳤다.",
      reference: "사사기 7:7",
    },
    {
      category: "인물",
      clue: "시어머니 나오미를 따라 베들레헴에 온 모압 여인",
      answer: "룻",
      explanation: "모압 여인 룻은 시어머니 나오미를 따라 베들레헴에 와 보아스와 결혼해 다윗의 증조모가 되었다.",
      reference: "룻기 1:16",
    },
    {
      category: "인물",
      clue: "룻과 결혼한 베들레헴의 부유한 기업 무를 자",
      answer: "보아스",
      explanation: "보아스는 기업 무를 자로서 룻과 결혼하여 오벳을 낳았고 다윗의 조상이 되었다.",
      reference: "룻기 4:13",
    },
    {
      category: "인물",
      clue: "갈멜 산에서 바알 선지자와 대결한 선지자",
      answer: "엘리야",
      explanation: "엘리야는 갈멜 산에서 바알 선지자들과 대결하여 하늘에서 불을 내려 여호와가 하나님이심을 증명했다.",
      reference: "열왕기상 18:38-39",
    },
    {
      category: "인물",
      clue: "엘리야의 갑절의 영감을 받은 후계 선지자",
      answer: "엘리사",
      explanation: "엘리사는 불수레로 승천하는 엘리야에게 갑절의 영감을 구하여 그의 사역을 이어받았다.",
      reference: "열왕기하 2:9",
    },
    {
      category: "인물",
      clue: "무너진 예루살렘 성벽을 재건한 총독",
      answer: "느헤미야",
      explanation: "느헤미야는 페르시아 왕의 허락을 받아 예루살렘으로 돌아가 오십이 일 만에 성벽을 재건했다.",
      reference: "느헤미야 6:15",
    },
    {
      category: "인물",
      clue: "사무엘이 기름 부은 이스라엘의 첫 왕",
      answer: "사울",
      explanation: "베냐민 지파 기스의 아들 사울은 사무엘에게 기름 부음을 받아 이스라엘의 첫 왕이 되었다.",
      reference: "사무엘상 10:1",
    },
  ],
  9: [
    {
      category: "구절",
      clue: "고린도전서 13장에서 믿음, 소망과 함께 든 가장 큰 것",
      answer: "사랑",
      explanation: "바울은 믿음과 소망과 사랑 중에 제일은 사랑이라고 가르쳤다.",
      reference: "고린도전서 13:13",
    },
    {
      category: "구절",
      clue: "에베소서가 말한, 구원이 행위가 아닌 무엇으로 됨",
      answer: "은혜",
      accepted: ["은혜와 믿음"],
      explanation: "바울은 너희가 그 은혜에 의하여 믿음으로 구원을 받았다고 가르쳤다.",
      reference: "에베소서 2:8",
    },
    {
      category: "구절",
      clue: "갈라디아서가 열거한 성령의 아홉 가지 열매의 첫 번째",
      answer: "사랑",
      explanation: "성령의 열매는 사랑, 희락, 화평 등 아홉 가지이며 그 첫째가 사랑이다.",
      reference: "갈라디아서 5:22",
    },
    {
      category: "구절",
      clue: "빌립보서가 말한, 모든 일을 능히 하게 하시는 분",
      answer: "그리스도",
      accepted: ["예수 그리스도", "주"],
      explanation: "바울은 내게 능력 주시는 그리스도 안에서 모든 것을 할 수 있다고 고백했다.",
      reference: "빌립보서 4:13",
    },
    {
      category: "구절",
      clue: "로마서가 말한, 죄의 삯이 무엇이라 함",
      answer: "사망",
      accepted: ["죽음"],
      explanation: "바울은 죄의 삯은 사망이요 하나님의 은사는 영생이라고 가르쳤다.",
      reference: "로마서 6:23",
    },
    {
      category: "인물",
      clue: "바울이 믿음의 아들이라 부른 젊은 목회자",
      answer: "디모데",
      explanation: "바울은 디모데를 믿음 안에서 참 아들이라 부르며 두 통의 서신으로 권면했다.",
      reference: "디모데전서 1:2",
    },
    {
      category: "구절",
      clue: "히브리서가 정의한, 바라는 것들의 실상이며 보지 못하는 것들의 증거",
      answer: "믿음",
      explanation: "히브리서는 믿음을 바라는 것들의 실상이요 보이지 않는 것들의 증거라고 정의한다.",
      reference: "히브리서 11:1",
    },
    {
      category: "구절",
      clue: "야고보서가 말한, 행함이 없는 그것은 죽은 것이라 함",
      answer: "믿음",
      explanation: "야고보는 행함이 없는 믿음은 그 자체가 죽은 것이라고 강조했다.",
      reference: "야고보서 2:17",
    },
    {
      category: "구절",
      clue: "요한일서가 선언한, 하나님은 곧 무엇이심",
      answer: "사랑",
      explanation: "요한은 하나님은 사랑이시라 선언하며 사랑 안에 거하는 자가 하나님 안에 거한다고 했다.",
      reference: "요한일서 4:8",
    },
    {
      category: "인물",
      clue: "바울이 빌레몬에게 용서를 부탁한 도망친 종",
      answer: "오네시모",
      explanation: "바울은 빌레몬서에서 도망친 종 오네시모를 형제로 받아 줄 것을 부탁했다.",
      reference: "빌레몬서 1:10",
    },
  ],
  10: [
    {
      category: "인물",
      clue: "밧모섬에서 요한계시록을 기록한 사도",
      answer: "요한",
      accepted: ["사도 요한"],
      explanation: "사도 요한은 밧모섬에서 주의 날에 환상을 받아 요한계시록을 기록했다.",
      reference: "요한계시록 1:9-10",
    },
    {
      category: "장소",
      clue: "요한이 환상을 받아 계시록을 기록한 섬",
      answer: "밧모섬",
      accepted: ["밧모", "밧모 섬"],
      explanation: "요한은 하나님의 말씀과 예수의 증거로 인하여 밧모라 하는 섬에 있었다.",
      reference: "요한계시록 1:9",
    },
    {
      category: "수",
      clue: "요한계시록에서 예수님이 편지를 보낸 아시아 교회의 수",
      answer: "일곱",
      accepted: ["7", "일곱 교회"],
      explanation: "요한계시록은 에베소를 비롯한 아시아의 일곱 교회에 보내는 편지로 시작한다.",
      reference: "요한계시록 1:11",
    },
    {
      category: "상징",
      clue: "죽임을 당하였으나 살아 두루마리를 펴기에 합당한 분",
      answer: "어린양",
      accepted: ["어린 양"],
      explanation: "오직 죽임을 당하신 어린양만이 인봉된 두루마리를 떼기에 합당하셨다.",
      reference: "요한계시록 5:6-9",
    },
    {
      category: "수",
      clue: "두루마리에 채워져 있던 봉인의 수",
      answer: "일곱",
      accepted: ["7", "일곱 인"],
      explanation: "안팎으로 쓰인 두루마리는 일곱 인으로 봉해져 있었고 어린양이 그것을 떼셨다.",
      reference: "요한계시록 5:1",
    },
    {
      category: "수",
      clue: "이스라엘 각 지파에서 인침 받은 자의 총수",
      answer: "십사만 사천",
      accepted: ["144000", "14만 4천", "십사만사천"],
      explanation: "이스라엘 열두 지파에서 각 일만 이천씩 모두 십사만 사천이 인침을 받았다.",
      reference: "요한계시록 7:4",
    },
    {
      category: "사건",
      clue: "마지막 때 천 년 동안 무저갱에 결박되는 자",
      answer: "사탄",
      accepted: ["마귀", "용", "사단"],
      explanation: "천사가 옛 뱀이요 마귀요 사탄인 용을 잡아 천 년 동안 무저갱에 결박했다.",
      reference: "요한계시록 20:2",
    },
    {
      category: "사건",
      clue: "사망과 음부가 던져지는 마지막 심판의 못",
      answer: "불못",
      accepted: ["불 못", "불의 못"],
      explanation: "마지막 심판에서 사망과 음부와 생명책에 없는 자들이 불못에 던져진다.",
      reference: "요한계시록 20:14-15",
    },
    {
      category: "장소",
      clue: "하늘에서 내려오는 거룩한 성, 새 무엇인가",
      answer: "새 예루살렘",
      accepted: ["거룩한 성 새 예루살렘"],
      explanation: "요한은 거룩한 성 새 예루살렘이 하나님께로부터 하늘에서 내려오는 것을 보았다.",
      reference: "요한계시록 21:2",
    },
    {
      category: "상징",
      clue: "예수님이 자신을 가리켜 처음과 마지막이라 하신 두 그리스 문자",
      answer: "알파와 오메가",
      accepted: ["알파 오메가"],
      explanation: "예수님은 자신을 알파와 오메가요 처음과 마지막이라 선언하셨다.",
      reference: "요한계시록 22:13",
    },
  ],
};

export const fillBlankQuestions: FillBlankQuestion[] = Object.entries(levelData).flatMap(([level, items]) =>
  items.map((item, index) => ({
    id: questionId(Number(level), "blank", index),
    level: Number(level),
    type: "fill_blank",
    category: item.category,
    difficulty: getDifficulty(Number(level)),
    question: `${item.clue}: ______`,
    payload: { blankLabel: item.category },
    answer: { text: item.answer, accepted: item.accepted },
    explanation: item.explanation,
    reference: item.reference,
  })),
);
