import type { MultipleChoiceQuestion } from "../bibleQuiz";
import { getDifficulty, questionId } from "./shared";

type QuizItem = {
  topic: string;
  question: string;
  choices: [string, string, string, string];
  answerIndex: number;
  explanation: string;
  reference: string;
};

const levelData: Record<number, QuizItem[]> = {
  1: [
    { topic: "천지창조", question: "하나님이 천지를 창조하실 때 첫째 날에 만드신 것은?", choices: ["사람", "빛", "바다", "별"], answerIndex: 1, explanation: "하나님이 첫째 날 '빛이 있으라' 하시니 빛이 있었습니다.", reference: "창세기 1:3" },
    { topic: "에덴동산", question: "에덴동산에서 하와를 꾀어 선악과를 먹게 한 것은?", choices: ["사자", "뱀", "독수리", "늑대"], answerIndex: 1, explanation: "뱀이 하와에게 선악과를 먹으라고 유혹했습니다.", reference: "창세기 3:1~6" },
    { topic: "노아의 방주", question: "방주를 지어 홍수에서 살아남은 사람은?", choices: ["아담", "아브라함", "노아", "모세"], answerIndex: 2, explanation: "하나님은 노아에게 방주를 짓게 하여 홍수에서 구원하셨습니다.", reference: "창세기 6:13~14" },
    { topic: "모세의 탄생", question: "갈대 상자에 담겨 나일 강에 띄워졌다가 구출된 사람은?", choices: ["여호수아", "모세", "사무엘", "다윗"], answerIndex: 1, explanation: "아기 모세가 갈대 상자에 담겨 나일 강에 띄워졌고 바로의 딸이 건져냈습니다.", reference: "출애굽기 2:3~10" },
    { topic: "십계명", question: "하나님이 시내 산에서 모세에게 주신 계명의 수는?", choices: ["5개", "7개", "10개", "12개"], answerIndex: 2, explanation: "하나님은 시내산에서 모세에게 열 가지 계명을 주셨습니다.", reference: "출애굽기 20:1~17" },
    { topic: "다윗과 골리앗", question: "물맷돌로 거인 골리앗을 쓰러뜨린 소년은?", choices: ["솔로몬", "사울", "다윗", "요나단"], answerIndex: 2, explanation: "다윗이 물매와 돌 하나로 블레셋 장수 골리앗을 쓰러뜨렸습니다.", reference: "사무엘상 17:49" },
    { topic: "솔로몬의 지혜", question: "다윗의 뒤를 이어 왕이 되어 지혜를 구한 왕은?", choices: ["솔로몬", "사울", "르호보암", "히스기야"], answerIndex: 0, explanation: "솔로몬은 왕위에 오른 후 하나님께 지혜를 구하는 기도를 드렸습니다.", reference: "열왕기상 3:9~12" },
    { topic: "다니엘", question: "사자 굴에 던져졌으나 살아난 사람은?", choices: ["다니엘", "요나", "엘리야", "에스겔"], answerIndex: 0, explanation: "다니엘은 기도를 멈추지 않아 사자 굴에 던져졌으나 하나님이 보호하셨습니다.", reference: "다니엘 6:22" },
    { topic: "요나", question: "큰 물고기 배 속에서 사흘을 지낸 선지자는?", choices: ["아모스", "요나", "호세아", "미가"], answerIndex: 1, explanation: "요나는 하나님의 명령을 피해 도망치다 큰 물고기에 삼켜져 사흘을 보냈습니다.", reference: "요나 1:17" },
    { topic: "예수님의 탄생", question: "예수님이 태어나신 곳은?", choices: ["나사렛", "예루살렘", "베들레헴", "가버나움"], answerIndex: 2, explanation: "예수님은 미가의 예언대로 유대 베들레헴에서 나셨습니다.", reference: "마태복음 2:1" },
    { topic: "세례 요한", question: "요단 강에서 예수님께 세례를 베푼 사람은?", choices: ["베드로", "세례 요한", "안드레", "빌립"], answerIndex: 1, explanation: "세례 요한이 요단강에서 예수님께 세례를 베풀었습니다.", reference: "마태복음 3:13~16" },
    { topic: "열두 제자", question: "예수님이 부르신 제자의 수는?", choices: ["7명", "10명", "12명", "70명"], answerIndex: 2, explanation: "예수님은 열두 명의 제자를 부르셨습니다.", reference: "마가복음 3:14" },
    { topic: "십자가", question: "예수님이 십자가에 못 박히신 곳은?", choices: ["감람산", "골고다", "시온산", "베다니"], answerIndex: 1, explanation: "예수님은 '해골의 곳'이라는 뜻의 골고다에서 십자가에 달리셨습니다.", reference: "마태복음 27:33" },
    { topic: "가나의 기적", question: "예수님이 가나의 혼인 잔치에서 행하신 첫 기적은?", choices: ["병자 치유", "물을 포도주로", "죽은 자 살림", "폭풍 잠재움"], answerIndex: 1, explanation: "예수님은 가나 혼인잔치에서 물을 포도주로 바꾸는 첫 표적을 행하셨습니다.", reference: "요한복음 2:9" },
    { topic: "예수님의 어머니", question: "예수님의 어머니의 이름은?", choices: ["마르다", "마리아", "한나", "엘리사벳"], answerIndex: 1, explanation: "예수님의 어머니는 마리아입니다.", reference: "마태복음 1:18" },
    { topic: "가룟 유다", question: "예수님을 은 삼십에 판 제자는?", choices: ["베드로", "도마", "가룟 유다", "요한"], answerIndex: 2, explanation: "가룟 유다가 은 삼십을 받고 예수님을 대제사장들에게 팔았습니다.", reference: "마태복음 26:14~15" },
    { topic: "시편 23편", question: "\"여호와는 나의 ○○이시니 내게 부족함이 없으리로다\"의 빈칸은?", choices: ["반석", "목자", "방패", "산성"], answerIndex: 1, explanation: "시편 23편 1절에서 다윗은 여호와를 '목자'로 고백했습니다.", reference: "시편 23:1" },
    { topic: "여호수아", question: "모세의 뒤를 이어 이스라엘을 가나안으로 인도한 지도자는?", choices: ["갈렙", "여호수아", "기드온", "사무엘"], answerIndex: 1, explanation: "여호수아가 모세의 뒤를 이어 이스라엘 백성을 가나안으로 이끌었습니다.", reference: "여호수아 1:1~2" },
    { topic: "만나", question: "광야에서 하나님이 하늘에서 내려 주신 양식은?", choices: ["만나", "메추라기", "무화과", "보리떡"], answerIndex: 0, explanation: "하나님은 광야에서 이스라엘 백성에게 하늘로부터 만나를 내려 주셨습니다.", reference: "출애굽기 16:15" },
    { topic: "오병이어", question: "떡 다섯 개와 물고기 두 마리로 먹인 사람의 수(남자 기준)는?", choices: ["500명", "1,000명", "5,000명", "10,000명"], answerIndex: 2, explanation: "예수님은 오병이어로 남자만 오천 명을 먹이셨습니다.", reference: "마태복음 14:21" },
  ],
  2: [
    { topic: "가인과 아벨", question: "아담과 하와의 첫째 아들로, 동생 아벨을 죽인 사람은?", choices: ["셋", "가인", "에녹", "라멕"], answerIndex: 1, explanation: "가인이 제물 문제로 동생 아벨을 시기하여 죽였습니다.", reference: "창세기 4:8" },
    { topic: "이삭", question: "아브라함이 백 세에 얻은 약속의 아들은?", choices: ["이스마엘", "이삭", "야곱", "에서"], answerIndex: 1, explanation: "하나님의 약속대로 아브라함이 백 세에 이삭을 낳았습니다.", reference: "창세기 21:5" },
    { topic: "무지개 언약", question: "하나님이 다시는 물로 심판하지 않겠다는 증표로 주신 것은?", choices: ["구름", "무지개", "별", "불기둥"], answerIndex: 1, explanation: "하나님은 무지개를 다시는 홍수로 멸하지 않겠다는 언약의 표로 주셨습니다.", reference: "창세기 9:13" },
    { topic: "룻", question: "시어머니 나오미를 따라간 모압 여인은?", choices: ["룻", "에스더", "드보라", "한나"], answerIndex: 0, explanation: "룻은 '어디로 가시든 나도 가겠나이다'라고 고백하며 나오미를 따라갔습니다.", reference: "룻기 1:16" },
    { topic: "이스라엘의 첫 왕", question: "이스라엘의 첫 번째 왕은?", choices: ["다윗", "사울", "솔로몬", "사무엘"], answerIndex: 1, explanation: "사무엘이 기름을 부어 사울을 이스라엘 최초의 왕으로 세웠습니다.", reference: "사무엘상 10:1" },
    { topic: "엘리야와 바알", question: "갈멜 산에서 바알 선지자들과 대결한 선지자는?", choices: ["엘리사", "엘리야", "이사야", "예레미야"], answerIndex: 1, explanation: "엘리야가 갈멜산에서 450명의 바알 선지자와 대결하여 하나님의 불을 내렸습니다.", reference: "열왕기상 18:38" },
    { topic: "나아만", question: "요단 강에 일곱 번 씻고 나병이 나은 아람 군대 장관은?", choices: ["나아만", "게하시", "고넬료", "하사엘"], answerIndex: 0, explanation: "나아만이 엘리사의 말대로 요단강에 일곱 번 몸을 잠그니 나병이 낫았습니다.", reference: "열왕기하 5:14" },
    { topic: "에스더", question: "\"죽으면 죽으리이다\"라 말하며 동족을 구한 페르시아 왕후는?", choices: ["드보라", "에스더", "미리암", "라합"], answerIndex: 1, explanation: "에스더가 왕 앞에 나아가 유대 민족을 하만의 음모에서 구했습니다.", reference: "에스더 4:16" },
    { topic: "욥", question: "모든 재산과 자녀를 잃고도 하나님을 원망하지 않은 의인은?", choices: ["욥", "노아", "요셉", "다니엘"], answerIndex: 0, explanation: "욥은 극심한 고난 속에서도 '여호와께서 주셨다가 가져가셨으니 찬양'이라 고백했습니다.", reference: "욥기 1:21~22" },
    { topic: "풀무불", question: "풀무불에 던져졌으나 타지 않은 다니엘의 세 친구가 아닌 사람은?", choices: ["사드락", "메삭", "아벳느고", "벨드사살"], answerIndex: 3, explanation: "벨드사살은 다니엘의 바벨론 이름으로, 풀무불 사건의 당사자가 아닙니다.", reference: "다니엘 3:23~27" },
    { topic: "선한 사마리아인", question: "길에서 강도 만난 사람을 도운 비유의 주인공은?", choices: ["제사장", "레위인", "선한 사마리아인", "바리새인"], answerIndex: 2, explanation: "제사장과 레위인은 지나쳤지만 사마리아인이 강도 만난 자를 도왔습니다.", reference: "누가복음 10:33" },
    { topic: "나사로", question: "죽은 지 나흘 된 나사로를 살리신 곳은?", choices: ["가나", "베다니", "나인", "여리고"], answerIndex: 1, explanation: "예수님은 베다니에서 죽은 지 나흘 된 나사로를 살리셨습니다.", reference: "요한복음 11:43~44" },
    { topic: "광야 시험", question: "예수님이 광야에서 40일 금식 후 받으신 것은?", choices: ["천사의 위로", "마귀의 시험", "군중의 환영", "제자들의 방문"], answerIndex: 1, explanation: "예수님은 40일 금식 후 마귀에게 세 가지 시험을 받으셨습니다.", reference: "마태복음 4:1~2" },
    { topic: "오순절", question: "오순절에 제자들에게 임한 사건은?", choices: ["성령 강림", "예수 재림", "부활", "승천"], answerIndex: 0, explanation: "오순절에 성령이 임하여 제자들이 방언으로 말하며 복음을 전했습니다.", reference: "사도행전 2:1~4" },
    { topic: "바울의 회심", question: "다메섹 길에서 회심한, 핍박자였던 사람은?", choices: ["바나바", "사울(바울)", "스데반", "실라"], answerIndex: 1, explanation: "교회를 핍박하던 사울이 다메섹 도상에서 부활하신 예수님을 만나 회심했습니다.", reference: "사도행전 9:3~5" },
    { topic: "고린도전서 13장", question: "고린도전서 13장에서 \"그 중에 제일\"이라 한 것은?", choices: ["믿음", "소망", "사랑", "지혜"], answerIndex: 2, explanation: "믿음, 소망, 사랑 중에 제일은 사랑이라 했습니다.", reference: "고린도전서 13:13" },
    { topic: "빌립보서", question: "\"내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라\"는 어느 서신?", choices: ["로마서", "빌립보서", "갈라디아서", "골로새서"], answerIndex: 1, explanation: "빌립보서 4장 13절에 기록된 바울의 고백입니다.", reference: "빌립보서 4:13" },
    { topic: "요한계시록", question: "요한계시록을 기록한 사도가 환상을 본 섬은?", choices: ["그레데", "구브로", "밧모", "멜리데"], answerIndex: 2, explanation: "사도 요한은 밧모섬에서 유배 중 요한계시록의 환상을 받았습니다.", reference: "요한계시록 1:9" },
    { topic: "바벨탑", question: "사람들이 하늘에 닿는 탑을 쌓다 언어가 혼잡해진 곳은?", choices: ["바벨", "니느웨", "소돔", "우르"], answerIndex: 0, explanation: "하나님이 바벨에서 언어를 혼잡하게 하셔서 사람들을 온 땅에 흩으셨습니다.", reference: "창세기 11:9" },
    { topic: "삼손", question: "사사 시대에 나귀 턱뼈로 적을 친 힘센 사사는?", choices: ["기드온", "삼손", "입다", "에훗"], answerIndex: 1, explanation: "삼손이 나귀 턱뼈로 블레셋 사람 천 명을 쳤습니다.", reference: "사사기 15:15" },
  ],
  3: [
    { topic: "에녹", question: "죽지 않고 하나님과 동행하다 데려감을 받은, 365세를 산 인물은?", choices: ["므두셀라", "에녹", "라멕", "셋"], answerIndex: 1, explanation: "에녹은 하나님과 동행하다 죽지 않고 하나님이 데려가셨습니다.", reference: "창세기 5:23~24" },
    { topic: "야곱의 사닥다리", question: "야곱이 돌베개를 베고 자다 하늘의 사닥다리를 본 곳은?", choices: ["브엘세바", "벧엘", "헤브론", "세겜"], answerIndex: 1, explanation: "야곱이 벧엘에서 잠을 자다 하늘까지 닿는 사닥다리 환상을 보았습니다.", reference: "창세기 28:18~19" },
    { topic: "가나안 정탐", question: "가나안 정탐 후 믿음으로 보고한 두 사람은?", choices: ["모세와 아론", "여호수아와 갈렙", "갈렙과 훌", "아론과 훌"], answerIndex: 1, explanation: "열두 정탐꾼 중 여호수아와 갈렙만 믿음으로 가나안을 취할 수 있다고 보고했습니다.", reference: "민수기 14:6~9" },
    { topic: "기드온", question: "횃불·나팔·항아리로 미디안 군대를 물리친 사사는?", choices: ["드보라", "기드온", "바락", "삼갈"], answerIndex: 1, explanation: "기드온이 삼백 명으로 횃불·나팔·항아리 전략을 써 미디안을 물리쳤습니다.", reference: "사사기 7:19~22" },
    { topic: "나단 선지자", question: "다윗을 책망하며 \"당신이 그 사람이라\"고 말한 선지자는?", choices: ["사무엘", "갓", "나단", "아히야"], answerIndex: 2, explanation: "나단 선지자가 비유를 들어 다윗의 죄를 책망하며 '당신이 그 사람'이라 했습니다.", reference: "사무엘하 12:7" },
    { topic: "엘리사", question: "엘리야가 하늘로 올라간 후 갑절의 영감을 받은 제자는?", choices: ["엘리사", "게하시", "미가야", "오바댜"], answerIndex: 0, explanation: "엘리사는 엘리야의 갑절 영감을 구했고 그것이 이루어졌습니다.", reference: "열왕기하 2:9~11" },
    { topic: "느헤미야", question: "바벨론 포로 후 예루살렘 성벽을 재건한 인물은?", choices: ["에스라", "느헤미야", "스룹바벨", "학개"], answerIndex: 1, explanation: "느헤미야가 반대 세력을 물리치고 52일 만에 예루살렘 성벽을 재건했습니다.", reference: "느헤미야 2:17~18" },
    { topic: "전도서", question: "\"헛되고 헛되며 모든 것이 헛되도다\"로 시작하는 책은?", choices: ["잠언", "전도서", "아가", "욥기"], answerIndex: 1, explanation: "전도서는 '헛되고 헛되며 모든 것이 헛되도다'라는 선포로 시작합니다.", reference: "전도서 1:2" },
    { topic: "시편 119편", question: "\"주의 말씀은 내 발에 ○이요 내 길에 빛이니이다\"의 빈칸은?", choices: ["빛", "등", "길", "반석"], answerIndex: 1, explanation: "시편 119편 105절 말씀입니다.", reference: "시편 119:105" },
    { topic: "임마누엘", question: "이사야가 예언한 \"임마누엘\"의 뜻은?", choices: ["평강의 왕", "하나님이 우리와 함께 계시다", "구원자", "영존하시는 아버지"], answerIndex: 1, explanation: "임마누엘은 '하나님이 우리와 함께 계시다'는 뜻입니다.", reference: "이사야 7:14" },
    { topic: "예레미야", question: "\"눈물의 선지자\"로 불리는 사람은?", choices: ["이사야", "예레미야", "에스겔", "다니엘"], answerIndex: 1, explanation: "예레미야는 많은 눈물로 백성의 죄를 슬퍼하여 '눈물의 선지자'로 불립니다.", reference: "예레미야애가" },
    { topic: "에스겔의 환상", question: "그발 강가에서 마른 뼈가 살아나는 환상을 본 선지자는?", choices: ["다니엘", "에스겔", "호세아", "스가랴"], answerIndex: 1, explanation: "에스겔이 그발 강가에서 마른 뼈들이 살아나는 환상을 받았습니다.", reference: "에스겔 37장" },
    { topic: "베드로의 실족", question: "풍랑 위를 걸으려다 빠져 예수님이 붙드신 제자는?", choices: ["요한", "베드로", "안드레", "야고보"], answerIndex: 1, explanation: "베드로가 물 위를 걷다 바람을 보고 두려워하여 빠졌고 예수님이 손을 잡아 주셨습니다.", reference: "마태복음 14:29~30" },
    { topic: "변화산", question: "예수님이 변화산에서 함께 대화하신 두 구약 인물은?", choices: ["아브라함과 다윗", "모세와 엘리야", "모세와 아론", "엘리야와 엘리사"], answerIndex: 1, explanation: "변화산에서 모세와 엘리야가 나타나 예수님과 함께 대화했습니다.", reference: "마태복음 17:3" },
    { topic: "바나바", question: "바울과 첫 전도 여행을 떠난 \"위로의 아들\"은?", choices: ["실라", "바나바", "디모데", "마가"], answerIndex: 1, explanation: "바나바는 '위로의 아들'이라는 뜻으로, 바울의 1차 전도여행 동반자였습니다.", reference: "사도행전 13:2, 4:36" },
    { topic: "스데반", question: "돌에 맞아 순교한 최초의 순교자는?", choices: ["야고보", "스데반", "빌립", "바나바"], answerIndex: 1, explanation: "스데반이 유대인들에게 돌에 맞아 기독교 최초의 순교자가 되었습니다.", reference: "사도행전 7:59~60" },
    { topic: "히브리서", question: "\"믿음은 바라는 것들의 실상이요...\"는 어느 서신?", choices: ["야고보서", "히브리서", "베드로전서", "로마서"], answerIndex: 1, explanation: "히브리서 11장 1절의 믿음 정의입니다.", reference: "히브리서 11:1" },
    { topic: "야고보서", question: "\"행함이 없는 믿음은 ○○ 것이라\"의 빈칸은?", choices: ["약한", "죽은", "헛된", "어린"], answerIndex: 1, explanation: "야고보서 2장 26절에서 행함이 없는 믿음은 죽은 것이라 했습니다.", reference: "야고보서 2:26" },
    { topic: "알파와 오메가", question: "요한계시록에서 예수님을 가리키는 \"알파와 ○○\"의 빈칸은?", choices: ["베타", "오메가", "감마", "시그마"], answerIndex: 1, explanation: "예수님은 '알파와 오메가, 처음과 마지막'이라 하셨습니다.", reference: "요한계시록 22:13" },
    { topic: "전도서 3장", question: "\"범사에 기한이 있고 천하 만사가 다 ○가 있나니\"의 빈칸은?", choices: ["뜻", "때", "복", "길"], answerIndex: 1, explanation: "전도서 3장 1절 말씀입니다.", reference: "전도서 3:1" },
  ],
  4: [
    { topic: "멜기세덱", question: "아브라함에게 빵과 포도주로 축복한 \"지극히 높으신 하나님의 제사장\"은?", choices: ["아비멜렉", "멜기세덱", "에브론", "마므레"], answerIndex: 1, explanation: "살렘 왕 멜기세덱이 빵과 포도주로 아브라함을 축복했습니다.", reference: "창세기 14:18" },
    { topic: "유월절", question: "유월절 어린 양의 피를 발라야 했던 곳은?", choices: ["지붕과 마당", "좌우 문설주와 인방", "제단과 문", "창문과 기둥"], answerIndex: 1, explanation: "이스라엘 백성은 좌우 문설주와 인방에 어린 양의 피를 발라 재앙을 피했습니다.", reference: "출애굽기 12:7" },
    { topic: "발람", question: "발락 왕이 이스라엘을 저주하려 부른 선지자는?", choices: ["발람", "바락", "베올", "벨라"], answerIndex: 0, explanation: "모압 왕 발락이 발람을 불러 이스라엘을 저주하려 했습니다.", reference: "민수기 22장" },
    { topic: "라합", question: "여리고성 정탐꾼을 숨겨주고 붉은 줄로 가족을 구한 기생은?", choices: ["들릴라", "라합", "룻", "아비가일"], answerIndex: 1, explanation: "라합이 정탐꾼을 숨겨주고 붉은 줄을 표로 달아 가족을 구원받았습니다.", reference: "여호수아 2:18" },
    { topic: "여로보암", question: "솔로몬 사후 북이스라엘의 첫 왕이 된 사람은?", choices: ["르호보암", "여로보암", "아합", "오므리"], answerIndex: 1, explanation: "왕국 분열 후 여로보암이 북이스라엘의 첫 번째 왕이 되었습니다.", reference: "열왕기상 12:20" },
    { topic: "이세벨", question: "아합 왕의 아내로 엘리야를 핍박한 사람은?", choices: ["이세벨", "아달랴", "마아가", "밧세바"], answerIndex: 0, explanation: "이세벨은 아합 왕의 아내로 바알 숭배를 퍼뜨리고 엘리야를 죽이려 했습니다.", reference: "열왕기상 21장" },
    { topic: "하만", question: "모르드개를 죽이려 세운 장대에 자신이 달린 사람은?", choices: ["하만", "하사엘", "산발랏", "도비야"], answerIndex: 0, explanation: "하만은 모르드개를 달려고 장대를 세웠으나 결국 자신이 달렸습니다.", reference: "에스더 7:9~10" },
    { topic: "벨사살의 연회", question: "벨사살 왕 잔치 때 벽의 글씨 \"메네 메네 데겔 우바르신\"을 해석한 사람은?", choices: ["다니엘", "에스겔", "느헤미야", "에스라"], answerIndex: 0, explanation: "다니엘이 벽에 쓰인 글씨를 해석하여 바벨론의 멸망을 예언했습니다.", reference: "다니엘 5:25~28" },
    { topic: "거듭남", question: "예수님이 니고데모에게 \"물과 ○○으로 나지 아니하면 하나님 나라에 들어갈 수 없다\"의 빈칸은?", choices: ["불", "성령", "말씀", "진리"], answerIndex: 1, explanation: "예수님은 니고데모에게 물과 성령으로 나야 한다고 가르치셨습니다.", reference: "요한복음 3:5" },
    { topic: "막달라 마리아", question: "부활하신 예수님을 처음 만나 \"동산지기\"로 오해한 여인은?", choices: ["마르다", "막달라 마리아", "살로메", "요안나"], answerIndex: 1, explanation: "막달라 마리아가 부활하신 예수님을 처음 만났으나 처음에 동산지기로 오해했습니다.", reference: "요한복음 20:14~16" },
    { topic: "고넬료", question: "베드로의 환상을 통해 복음이 열린, 세례받은 로마 백부장은?", choices: ["고넬료", "율리오", "글라우디오", "누가"], answerIndex: 0, explanation: "고넬료 사건으로 이방인에게도 성령과 구원이 열렸습니다.", reference: "사도행전 10장" },
    { topic: "아레오바고", question: "바울이 \"알지 못하는 신에게\"라는 제단을 인용하며 전도한 곳은?", choices: ["에베소 극장", "아레오바고", "솔로몬 행각", "두란노 서원"], answerIndex: 1, explanation: "바울이 아테네 아레오바고에서 창조주 하나님을 전도했습니다.", reference: "사도행전 17:22~23" },
    { topic: "빌레몬서", question: "바울이 도망친 종 오네시모를 위해 그 주인에게 보낸 가장 짧은 서신은?", choices: ["디도서", "빌레몬서", "유다서", "빌립보서"], answerIndex: 1, explanation: "빌레몬서는 오네시모를 형제로 받아달라는 바울의 짧은 친서입니다.", reference: "빌레몬서 1:10~12" },
    { topic: "감사한 나병환자", question: "열 명의 나병환자 중 돌아와 감사한 한 사람은 어느 민족?", choices: ["로마인", "사마리아인", "헬라인", "애굽인"], answerIndex: 1, explanation: "열 명 중 유일하게 돌아와 감사한 사람은 사마리아인이었습니다.", reference: "누가복음 17:15~16" },
    { topic: "새 언약", question: "예레미야가 예언한 \"새 언약\"은 율법을 어디에 기록하신다 했나?", choices: ["돌판", "그들의 마음", "두루마리", "성전 벽"], answerIndex: 1, explanation: "예레미야는 새 언약 때 율법이 마음판에 기록될 것을 예언했습니다.", reference: "예레미야 31:33" },
    { topic: "이사야의 소명", question: "이사야 6장에서 스랍이 외친 \"거룩\"의 반복 횟수는?", choices: ["한 번", "두 번", "세 번", "일곱 번"], answerIndex: 2, explanation: "스랍들이 '거룩하다 거룩하다 거룩하다 만군의 여호와'라고 세 번 외쳤습니다.", reference: "이사야 6:3" },
    { topic: "참회시", question: "다윗이 밧세바 사건 후 지은 참회시는 시편 몇 편인가?", choices: ["22편", "23편", "51편", "119편"], answerIndex: 2, explanation: "시편 51편 표제에 '다윗이 밧세바와 통간한 후' 지은 시임이 기록되어 있습니다.", reference: "시편 51편 표제" },
    { topic: "부자와 나사로", question: "부자와 거지 나사로 비유에서 나사로가 죽은 후 안긴 곳은?", choices: ["낙원", "아브라함의 품", "셋째 하늘", "새 예루살렘"], answerIndex: 1, explanation: "나사로가 죽어 천사들에게 받들려 아브라함의 품에 안겼습니다.", reference: "누가복음 16:22" },
    { topic: "죄와 하나님의 영광", question: "\"모든 사람이 죄를 범하였으매 하나님의 ○○에 이르지 못하더니\"의 빈칸은?", choices: ["사랑", "영광", "은혜", "평강"], answerIndex: 1, explanation: "로마서 3장 23절 말씀입니다.", reference: "로마서 3:23" },
    { topic: "엔돌의 신접한 여인", question: "사울이 엔돌의 신접한 여인을 통해 불러낸 죽은 선지자는?", choices: ["나단", "사무엘", "갓", "엘리"], answerIndex: 1, explanation: "사울이 엔돌의 신접한 여인을 통해 죽은 사무엘을 불러냈습니다.", reference: "사무엘상 28:11~14" },
  ],
  5: [
    { topic: "까마귀", question: "노아가 물이 줄었는지 알아보려고 방주에서 가장 먼저 내보낸 새는?", choices: ["비둘기", "까마귀", "참새", "독수리"], answerIndex: 1, explanation: "노아가 까마귀를 먼저 내보냈고 이후 비둘기를 내보냈습니다.", reference: "창세기 8:7" },
    { topic: "속죄일", question: "레위기에서 대제사장이 1년에 한 번 지성소에 들어가던 날은?", choices: ["초막절", "속죄일", "무교절", "칠칠절"], answerIndex: 1, explanation: "대제사장은 속죄일에만 지성소에 들어가 백성의 죄를 속했습니다.", reference: "레위기 16:29~34" },
    { topic: "하나님의 이름", question: "하나님이 떨기나무에서 모세에게 알려주신 이름의 표현은?", choices: ["\"전능한 자\"", "\"나는 스스로 있는 자이니라\"", "\"만군의 여호와\"", "\"거룩하신 자\""], answerIndex: 1, explanation: "하나님은 '나는 스스로 있는 자'(에흐예)라고 이름을 알려 주셨습니다.", reference: "출애굽기 3:14" },
    { topic: "느부갓네살", question: "남유다 멸망 시 예루살렘 성전을 불태운 바벨론 왕은?", choices: ["벨사살", "느부갓네살", "다리오", "고레스"], answerIndex: 1, explanation: "느부갓네살 왕이 예루살렘을 함락하고 성전을 불태웠습니다.", reference: "열왕기하 25:8~9" },
    { topic: "하박국", question: "\"무화과나무가 무성치 못하여도 즐거워하리로다\"라고 고백한 선지자는?", choices: ["하박국", "스바냐", "나훔", "요엘"], answerIndex: 0, explanation: "하박국은 아무것도 없어도 여호와로 인해 즐거워하겠다고 고백했습니다.", reference: "하박국 3:17~18" },
    { topic: "말라기의 약속", question: "말라기에서 \"온전한 십일조를 들이고 나를 시험하라\"며 약속하신 것은?", choices: ["땅의 평화", "하늘 문을 열어 복을 부으심", "자손의 번성", "적의 멸망"], answerIndex: 1, explanation: "하나님은 십일조를 드리면 하늘 문을 열어 복을 붓겠다고 약속하셨습니다.", reference: "말라기 3:10" },
    { topic: "놋 땅", question: "가인이 아벨을 죽인 후 쫓겨나 거주한 땅의 이름은?", choices: ["우르", "놋", "하란", "고센"], answerIndex: 1, explanation: "가인은 에덴 동쪽 놋 땅으로 쫓겨나 거주했습니다.", reference: "창세기 4:16" },
    { topic: "혈루증 여인", question: "열두 해 혈루증을 앓던 여인이 나음받기 위해 만진 것은?", choices: ["예수님의 손", "예수님의 옷자락", "베드로의 그림자", "성전 휘장"], answerIndex: 1, explanation: "혈루증 여인이 예수님의 옷자락을 만지자 즉시 나았습니다.", reference: "마가복음 5:27~29" },
    { topic: "달란트 비유", question: "달란트 비유에서 한 달란트 받은 종이 그 돈을 어떻게 했나?", choices: ["장사에 썼다", "은행에 맡겼다", "땅을 파고 감추었다", "가난한 자에게 주었다"], answerIndex: 2, explanation: "한 달란트 받은 종은 두려워 땅을 파고 감추었다가 책망받았습니다.", reference: "마태복음 25:18" },
    { topic: "라오디게아 교회", question: "요한계시록에서 \"차지도 덥지도 않다\"고 책망받은 교회는?", choices: ["에베소", "서머나", "라오디게아", "빌라델비아"], answerIndex: 2, explanation: "라오디게아 교회는 미지근하다는 책망을 받았습니다.", reference: "요한계시록 3:15~16" },
    { topic: "일곱 인", question: "어린 양만이 떼실 수 있던 인봉된 두루마리의 인은 모두 몇 개?", choices: ["세 개", "다섯 개", "일곱 개", "열두 개"], answerIndex: 2, explanation: "두루마리에는 일곱 인이 봉해져 있었고 어린 양만이 뗄 수 있었습니다.", reference: "요한계시록 5:1" },
    { topic: "새 예루살렘", question: "새 예루살렘에 해와 달이 필요 없는 이유는?", choices: ["항상 낮이라서", "하나님의 영광이 비치고 어린 양이 등불이 되심", "별빛이 가득해서", "불기둥이 있어서"], answerIndex: 1, explanation: "하나님의 영광이 비치고 어린 양이 등불이 되므로 해와 달이 필요 없습니다.", reference: "요한계시록 21:23" },
    { topic: "베드로후서", question: "베드로후서에서 \"주께는 하루가 천 년 같고 천 년이 ○○ 같다\"의 빈칸은?", choices: ["한 순간", "하루", "한 시간", "한 달"], answerIndex: 1, explanation: "베드로후서 3장 8절 말씀입니다.", reference: "베드로후서 3:8" },
    { topic: "현숙한 여인", question: "잠언 31장의 \"현숙한 여인\"의 값은 무엇보다 귀하다 했나?", choices: ["금", "진주", "은", "보석함"], answerIndex: 1, explanation: "잠언 31장 10절에서 현숙한 여인의 값은 진주보다 귀하다 했습니다.", reference: "잠언 31:10" },
    { topic: "전도자", question: "전도서가 저자를 소개하는 또 다른 이름(직책)은?", choices: ["선견자", "전도자(코헬렛)", "제사장", "서기관"], answerIndex: 1, explanation: "전도서 1장 1절에서 저자를 '전도자(코헬렛)'로 소개합니다.", reference: "전도서 1:1" },
    { topic: "우리아 사건", question: "다윗이 우리아를 죽게 하려고 요압에게 내린 명령은?", choices: ["독을 먹이라", "맹렬한 싸움 앞에 세우고 후퇴하라", "감옥에 가두라", "멀리 보내라"], answerIndex: 1, explanation: "다윗은 요압에게 우리아를 맹렬한 싸움 앞에 세우고 후퇴하도록 명령했습니다.", reference: "사무엘하 11:15" },
    { topic: "생령", question: "하나님이 아담에게 생기를 불어넣어 사람이 \"생령\"이 되었다고 기록한 절은?", choices: ["창세기 1:27", "창세기 2:7", "창세기 1:1", "창세기 2:21"], answerIndex: 1, explanation: "창세기 2장 7절에 생기를 불어넣어 사람이 생령이 되었다고 기록되어 있습니다.", reference: "창세기 2:7" },
    { topic: "이스마엘", question: "하갈이 낳은 아브라함의 첫째 아들의 이름은?", choices: ["이삭", "이스마엘", "에서", "미디안"], answerIndex: 1, explanation: "하갈이 아브라함에게서 이스마엘을 낳았습니다.", reference: "창세기 16:15" },
    { topic: "천사의 탄생 선포", question: "누가복음에서 양 치던 목자들에게 예수 탄생을 처음 전한 존재는?", choices: ["동방박사", "주의 사자(천사)", "세례 요한", "시므온"], answerIndex: 1, explanation: "주의 사자가 목자들에게 나타나 베들레헴에서 탄생하신 구주를 알렸습니다.", reference: "누가복음 2:8~11" },
    { topic: "맹인 치유", question: "예수님이 날 때부터 맹인 된 사람의 눈을 뜨게 하실 때 사용하신 것은?", choices: ["손을 얹으심", "침으로 진흙을 이겨 바르심", "물을 뿌리심", "말씀만 하심"], answerIndex: 1, explanation: "예수님이 침으로 진흙을 이겨 맹인의 눈에 바르시고 실로암 못에서 씻으라 하셨습니다.", reference: "요한복음 9:6~7" },
  ],
  6: [
    { topic: "레아의 첫째 아들", question: "야곱의 열두 아들 중 레아가 낳은 첫째 아들은?", choices: ["르우벤", "시므온", "유다", "요셉"], answerIndex: 0, explanation: "레아가 야곱에게서 낳은 첫째 아들은 르우벤입니다.", reference: "창세기 29:32" },
    { topic: "에브라임과 므낫세", question: "요셉의 두 아들로, 야곱이 축복한 형제는?", choices: ["에브라임과 므낫세", "베냐민과 단", "갓과 아셀", "잇사갈과 스불론"], answerIndex: 0, explanation: "야곱이 임종 전 요셉의 두 아들 에브라임과 므낫세를 양자로 삼고 축복했습니다.", reference: "창세기 48:1, 48:14" },
    { topic: "초대 대제사장", question: "모세의 형으로 초대 대제사장이 된 사람은?", choices: ["아론", "훌", "엘르아살", "비느하스"], answerIndex: 0, explanation: "아론이 이스라엘의 초대 대제사장으로 세워졌습니다.", reference: "출애굽기 28:1" },
    { topic: "미리암", question: "모세의 누이로, 홍해를 건넌 후 소고를 들고 찬양한 여선지자는?", choices: ["미리암", "드보라", "훌다", "안나"], answerIndex: 0, explanation: "미리암이 소고를 들고 홍해 도하 후 찬양을 이끌었습니다.", reference: "출애굽기 15:20" },
    { topic: "드보라", question: "사사 중 여선지자로, 바락과 함께 시스라 군대를 물리친 사람은?", choices: ["드보라", "야엘", "미리암", "한나"], answerIndex: 0, explanation: "드보라는 여선지자이자 사사로 바락과 함께 시스라 군대를 물리쳤습니다.", reference: "사사기 4:4~9" },
    { topic: "야엘", question: "시스라의 머리에 장막 말뚝을 박아 죽인 여인은?", choices: ["야엘", "드보라", "들릴라", "라합"], answerIndex: 0, explanation: "야엘이 장막 안에 피신한 시스라를 말뚝으로 죽였습니다.", reference: "사사기 4:21" },
    { topic: "요압", question: "다윗의 군대 장관으로, 압살롬을 죽인 사람은?", choices: ["요압", "아비새", "아마사", "브나야"], answerIndex: 0, explanation: "다윗의 군대 장관 요압이 나무에 걸린 압살롬을 죽였습니다.", reference: "사무엘하 18:14" },
    { topic: "밧세바", question: "솔로몬의 어머니는?", choices: ["밧세바", "아비가일", "미갈", "아히노암"], answerIndex: 0, explanation: "밧세바가 다윗과의 사이에서 솔로몬을 낳았습니다.", reference: "사무엘하 12:24" },
    { topic: "아히도벨", question: "다윗을 도왔으나 나중에 그를 배반하고 압살롬 편에 선 모사는?", choices: ["아히도벨", "후새", "나단", "시므이"], answerIndex: 0, explanation: "아히도벨이 압살롬의 반역 때 다윗을 배반하고 압살롬을 도왔습니다.", reference: "사무엘하 15:31" },
    { topic: "엘리사의 첫 기적", question: "\"엘리야\"가 아니라 그의 후계자로서 엘리사가 처음 행한 기적은?", choices: ["요단 강을 가름", "죽은 아이를 살림", "도끼를 떠오르게 함", "물을 고침"], answerIndex: 0, explanation: "엘리사가 엘리야의 겉옷으로 요단강을 가른 것이 첫 기적입니다.", reference: "열왕기하 2:14" },
    { topic: "통일 왕국 마지막 왕", question: "북이스라엘과 남유다, 두 왕국으로 나뉘기 직전의 통일 왕국 마지막 왕은?", choices: ["솔로몬", "르호보암", "사울", "다윗"], answerIndex: 0, explanation: "솔로몬 사후 왕국이 분열되었으므로 솔로몬이 통일 왕국 마지막 왕입니다.", reference: "열왕기상 11:42~43" },
    { topic: "요시야의 종교개혁", question: "남유다 왕 중, 종교개혁을 단행하고 율법책을 발견한 왕은?", choices: ["요시야", "히스기야", "아사", "여호사밧"], answerIndex: 0, explanation: "요시야 왕 때 성전에서 율법책이 발견되어 대대적인 종교개혁이 이루어졌습니다.", reference: "열왕기하 22:8~11" },
    { topic: "히스기야의 기도", question: "앗수르 산헤립의 침공 때, 하나님께 기도하여 위기를 넘긴 남유다 왕은?", choices: ["히스기야", "요시야", "웃시야", "아하스"], answerIndex: 0, explanation: "히스기야가 산헤립의 편지를 성전에 펴놓고 기도했고 하나님이 응답하셨습니다.", reference: "열왕기하 19:14~19" },
    { topic: "이사야 활동 시대", question: "선지자 이사야가 활동한 시대의 남유다 왕이 아닌 사람은?", choices: ["여로보암", "웃시야", "아하스", "히스기야"], answerIndex: 0, explanation: "이사야서 1장 1절은 웃시야, 요담, 아하스, 히스기야 때 활동했다고 기록합니다. 여로보암은 북이스라엘 왕입니다.", reference: "이사야 1:1" },
    { topic: "요엘", question: "12소선지서 중 \"여호와의 날\"을 메뚜기 재앙과 함께 강조한 선지자는?", choices: ["요엘", "아모스", "오바댜", "학개"], answerIndex: 0, explanation: "요엘은 메뚜기 재앙을 통해 여호와의 날을 경고했습니다.", reference: "요엘 1:4, 2:1" },
    { topic: "오바댜", question: "에돔의 멸망을 예언한, 구약에서 가장 짧은 책은?", choices: ["오바댜", "학개", "나훔", "하박국"], answerIndex: 0, explanation: "오바댜서는 구약에서 가장 짧은 책으로 에돔의 교만과 멸망을 예언합니다.", reference: "오바댜 1장" },
    { topic: "사가랴", question: "세례 요한의 아버지로, 한동안 말을 못 하게 된 제사장은?", choices: ["사가랴", "시므온", "아나니아", "그레스보"], answerIndex: 0, explanation: "사가랴가 성전에서 가브리엘 천사의 말을 믿지 않아 말을 못 하게 되었습니다.", reference: "누가복음 1:20" },
    { topic: "마태", question: "예수님의 열두 제자 중 \"세리\" 출신은?", choices: ["마태(레위)", "베드로", "빌립", "도마"], answerIndex: 0, explanation: "마태(레위)는 세리였으나 예수님의 부르심에 즉시 따랐습니다.", reference: "마태복음 9:9" },
    { topic: "도마의 고백", question: "예수님을 \"내 주시며 내 하나님이시니이다\"라고 고백한, 의심 많던 제자는?", choices: ["도마", "빌립", "나다나엘", "안드레"], answerIndex: 0, explanation: "부활하신 예수님의 손과 옆구리를 확인한 도마가 '내 주시며 내 하나님'이라 고백했습니다.", reference: "요한복음 20:28" },
    { topic: "마가 요한", question: "사도행전에서 바울 대신 1차 전도 여행 중간에 떠나 다툼의 원인이 된 사람은?", choices: ["마가 요한", "디모데", "누가", "디도"], answerIndex: 0, explanation: "마가 요한이 1차 전도여행 중 이탈하여 바울과 바나바의 2차 전도여행 동행 여부에 대한 다툼이 생겼습니다.", reference: "사도행전 15:37~39" },
  ],
  7: [
    { topic: "아비멜렉(아브라함)", question: "아브라함이 아내를 누이라 속인 두 왕 중, 그랄 왕의 이름은?", choices: ["아비멜렉", "바로", "멜기세덱", "그돌라오멜"], answerIndex: 0, explanation: "아브라함이 사라를 누이라 속인 그랄 왕은 아비멜렉입니다.", reference: "창세기 20:2" },
    { topic: "아비멜렉(이삭)", question: "이삭도 아내 리브가를 누이라 속였던 그랄 땅의 왕 이름 역시?", choices: ["아비멜렉", "헤스본", "시혼", "옥"], answerIndex: 0, explanation: "이삭 때도 그랄 왕의 이름이 아비멜렉이었습니다.", reference: "창세기 26:7~8" },
    { topic: "므리바(가데스)", question: "광야에서 모세가 반석을 쳐 물을 낸 두 사건 중, 가나안 입성을 막은 두 번째 장소는?", choices: ["므리바(가데스)", "르비딤", "마라", "엘림"], answerIndex: 0, explanation: "므리바(가데스)에서 모세가 반석을 쳐 물을 냈으나 하나님의 말씀을 어겨 가나안 입성이 막혔습니다.", reference: "민수기 20:11~12" },
    { topic: "맛사와 므리바", question: "모세가 처음 반석을 쳐 물을 낸 곳(르비딤)에서 그 장소에 붙인 이름은?", choices: ["맛사와 므리바", "마라", "엘림", "신 광야"], answerIndex: 0, explanation: "르비딤에서 반석을 쳐 물을 낸 장소를 맛사와 므리바라 불렀습니다.", reference: "출애굽기 17:7" },
    { topic: "겉옷 자락", question: "다윗이 사울을 죽일 기회를 얻고도 살려준 두 사건 중, 엔게디 굴에서 자른 것은?", choices: ["겉옷 자락", "머리카락", "창과 물병", "신발"], answerIndex: 0, explanation: "다윗이 엔게디 굴에서 자는 사울의 겉옷 자락만 자르고 살려 보냈습니다.", reference: "사무엘상 24:4" },
    { topic: "창과 물병", question: "다윗이 사울의 진영에서 잠든 사울 곁에서 가져온 두 가지는?", choices: ["창과 물병", "칼과 방패", "겉옷과 띠", "활과 화살"], answerIndex: 0, explanation: "두 번째 사건에서 다윗은 사울의 창과 물병을 가져왔습니다.", reference: "사무엘상 26:12" },
    { topic: "수넴 여인", question: "엘리야와 엘리사가 각각 살린 아이가 있는데, 엘리사가 살린 아이의 어머니는 어느 지역 여인?", choices: ["수넴", "사르밧", "나인", "그릿"], answerIndex: 0, explanation: "엘리사는 수넴 여인의 아들을 살렸습니다.", reference: "열왕기하 4:32~35" },
    { topic: "사르밧 과부", question: "엘리야가 살린 아이의 어머니, 즉 그를 먹여 살린 과부는 어느 지역 사람?", choices: ["사르밧", "수넴", "다메섹", "길르앗"], answerIndex: 0, explanation: "사르밧 과부가 엘리야를 먹여 살렸고 엘리야가 그 아들을 살렸습니다.", reference: "열왕기상 17:9, 17:22" },
    { topic: "야이로", question: "예수님이 회당장의 딸을 살리신 사건에서, 그 회당장의 이름은?", choices: ["야이로", "니고데모", "시몬", "글로바"], answerIndex: 0, explanation: "야이로의 딸이 죽었으나 예수님이 살리셨습니다.", reference: "마가복음 5:22" },
    { topic: "나인 과부의 아들", question: "예수님이 과부의 죽은 아들을 살리신 마을은?", choices: ["나인", "베다니", "가버나움", "벳새다"], answerIndex: 0, explanation: "예수님이 나인 성문 밖에서 과부의 죽은 아들을 살리셨습니다.", reference: "누가복음 7:11~15" },
    { topic: "칠병이어", question: "오병이어(5병2어)와 칠병이어를 구분할 때, 칠병이어로 먹인 사람의 수는?", choices: ["사천 명", "오천 명", "삼천 명", "만 명"], answerIndex: 0, explanation: "칠병이어로 사천 명(남자)을 먹이셨습니다.", reference: "마태복음 15:34~38" },
    { topic: "오병이어 남은 광주리", question: "오병이어 후 남은 조각을 담은 광주리는 몇 개였나?", choices: ["열두 광주리", "일곱 광주리", "다섯 광주리", "세 광주리"], answerIndex: 0, explanation: "오병이어 후 열두 광주리가 남았습니다.", reference: "마태복음 14:20" },
    { topic: "칠병이어 남은 광주리", question: "칠병이어 후 남은 조각을 담은 광주리는 몇 개였나?", choices: ["일곱 광주리", "열두 광주리", "다섯 광주리", "열 광주리"], answerIndex: 0, explanation: "칠병이어 후 일곱 광주리가 남았습니다.", reference: "마태복음 15:37" },
    { topic: "베드로의 부인", question: "베드로가 예수님을 부인한 횟수와, 그 신호가 된 것은?", choices: ["세 번, 닭 울기 전", "두 번, 해 뜨기 전", "세 번, 나팔 소리", "한 번, 새벽"], answerIndex: 0, explanation: "베드로는 닭 울기 전 세 번 예수님을 부인했습니다.", reference: "마태복음 26:34, 26:75" },
    { topic: "다 이루었다", question: "예수님이 십자가에서 하신 \"가상칠언\" 중, \"다 이루었다\"는 어느 복음서에 기록?", choices: ["요한복음", "마태복음", "마가복음", "누가복음"], answerIndex: 0, explanation: "요한복음 19장 30절에 '다 이루었다'는 말씀이 기록되어 있습니다.", reference: "요한복음 19:30" },
    { topic: "엘리 엘리", question: "\"엘리 엘리 라마 사박다니\"(나의 하나님 나를 버리셨나이까)는 어느 복음서?", choices: ["마태복음", "누가복음", "요한복음", "사도행전"], answerIndex: 0, explanation: "마태복음 27장 46절에 기록되어 있습니다.", reference: "마태복음 27:46" },
    { topic: "엠마오 제자", question: "부활 후 엠마오로 가던 두 제자에게 나타나신 예수님을 알아본 순간은?", choices: ["떡을 떼실 때", "손의 못자국을 볼 때", "이름을 부르실 때", "성경을 펴실 때"], answerIndex: 0, explanation: "예수님이 떡을 떼어 나누실 때 제자들이 그분을 알아보았습니다.", reference: "누가복음 24:30~31" },
    { topic: "유다의 죽음(마태)", question: "가룟 유다가 죽은 방식에 대해 마태복음이 기록한 것은?", choices: ["스스로 목매어 죽음", "몸이 곤두박질하여 터짐", "돌에 맞아 죽음", "병들어 죽음"], answerIndex: 0, explanation: "마태복음 27장 5절에 유다가 스스로 목매어 죽었다고 기록합니다.", reference: "마태복음 27:5" },
    { topic: "유다의 죽음(사도행전)", question: "사도행전이 기록한 유다의 최후는?", choices: ["몸이 곤두박질하여 배가 터짐", "목매어 죽음", "칼에 찔림", "익사"], answerIndex: 0, explanation: "사도행전 1장 18절에 유다가 곤두박질하여 배가 터졌다고 기록합니다.", reference: "사도행전 1:18" },
    { topic: "맛디아", question: "유다의 자리를 대신해 사도로 제비뽑힌 사람은?", choices: ["맛디아", "바사바(요셉)", "바나바", "실라"], answerIndex: 0, explanation: "제비뽑기로 맛디아가 열두 사도의 자리를 채웠습니다.", reference: "사도행전 1:26" },
  ],
  8: [
    { topic: "방주의 크기", question: "노아의 방주의 길이는 얼마였나?", choices: ["삼백 규빗", "백오십 규빗", "오백 규빗", "백 규빗"], answerIndex: 0, explanation: "방주의 길이는 삼백 규빗, 너비 오십 규빗, 높이 삼십 규빗이었습니다.", reference: "창세기 6:15" },
    { topic: "야곱의 14년", question: "야곱이 라반의 집에서 두 아내를 얻기 위해 일한 총 햇수는?", choices: ["14년", "7년", "20년", "21년"], answerIndex: 0, explanation: "레아를 위해 7년, 라헬을 위해 7년, 총 14년을 일했습니다.", reference: "창세기 31:41" },
    { topic: "광야 40년", question: "이스라엘 백성이 광야에서 방황한 햇수는?", choices: ["40년", "70년", "400년", "430년"], answerIndex: 0, explanation: "정탐꾼들의 불신 보고로 40년간 광야를 방황하게 되었습니다.", reference: "민수기 14:33~34" },
    { topic: "애굽 거주 430년", question: "이스라엘이 애굽에 거주한 햇수로 출애굽기가 기록한 것은?", choices: ["430년", "400년", "40년", "215년"], answerIndex: 0, explanation: "출애굽기 12장 40절에 애굽 거주 기간을 430년으로 기록합니다.", reference: "출애굽기 12:40" },
    { topic: "성전 건축 기간", question: "솔로몬 성전 건축에 걸린 햇수는?", choices: ["7년", "13년", "20년", "3년 반"], answerIndex: 0, explanation: "솔로몬이 성전을 짓는 데 7년이 걸렸습니다.", reference: "열왕기상 6:38" },
    { topic: "바벨론 포로 70년", question: "바벨론 포로 기간을 예레미야가 예언한 햇수는?", choices: ["70년", "40년", "400년", "490년"], answerIndex: 0, explanation: "예레미야는 바벨론 포로 기간이 70년이라고 예언했습니다.", reference: "예레미야 25:11" },
    { topic: "칠십 이레", question: "다니엘이 받은 \"이레(주)\"의 환상에서, 정해진 총 이레의 수는?", choices: ["칠십 이레", "일곱 이레", "육십이 이레", "사백 이레"], answerIndex: 0, explanation: "다니엘 9장 24절에 '칠십 이레'가 정해졌다고 합니다.", reference: "다니엘 9:24" },
    { topic: "욥의 딸들", question: "욥에게 마지막에 회복되어 태어난 딸은 모두 몇 명?", choices: ["세 명", "일곱 명", "열 명", "다섯 명"], answerIndex: 0, explanation: "욥기 42장에 욥이 회복된 후 딸 셋을 낳았습니다.", reference: "욥기 42:13~14" },
    { topic: "일곱 번 기도", question: "엘리야가 갈멜 산에서 비를 위해 기도할 때, 종을 바다 쪽으로 보낸 횟수는?", choices: ["일곱 번", "세 번", "열 번", "열두 번"], answerIndex: 0, explanation: "엘리야가 종을 일곱 번째 보냈을 때 비구름이 올라왔습니다.", reference: "열왕기상 18:43" },
    { topic: "용서의 횟수", question: "예수님이 베드로에게 \"일곱 번을 일흔 번까지라도\" 용서하라 하신 것은 몇 번을 의미?", choices: ["사실상 무한정", "정확히 490번", "77번", "70번"], answerIndex: 0, explanation: "이 표현은 횟수를 세지 말고 무한히 용서하라는 의미입니다.", reference: "마태복음 18:22" },
    { topic: "부활 후 40일", question: "예수님이 부활하신 후 승천 전까지 제자들에게 보이신 기간은?", choices: ["40일", "50일", "7일", "3일"], answerIndex: 0, explanation: "예수님은 부활 후 40일 동안 제자들에게 나타나 하나님 나라를 가르치셨습니다.", reference: "사도행전 1:3" },
    { topic: "오순절 50일", question: "오순절은 부활(유월절) 이후 며칠째 되는 날인가?", choices: ["50일째", "40일째", "7일째", "30일째"], answerIndex: 0, explanation: "오순절은 첫 열매 다음 날부터 50일째 되는 날입니다.", reference: "레위기 23:15~16" },
    { topic: "아나니아(다메섹)", question: "바울이 다메섹에서 회심 후 시력을 회복시켜 준 제자의 이름은?", choices: ["아나니아", "바나바", "스데반", "빌립"], answerIndex: 0, explanation: "다메섹의 제자 아나니아가 바울에게 안수하여 시력이 회복되었습니다.", reference: "사도행전 9:17~18" },
    { topic: "아나니아와 삽비라", question: "사도행전에서 헌금을 속였다가 즉사한 부부의 이름은?", choices: ["아나니아와 삽비라", "아굴라와 브리스길라", "보아스와 룻", "엘가나와 한나"], answerIndex: 0, explanation: "아나니아와 삽비라 부부가 헌금의 일부를 감추고 거짓말하다 즉사했습니다.", reference: "사도행전 5:1~10" },
    { topic: "브리스길라와 아굴라", question: "바울과 함께 천막 짓는 일을 하며 동역한 부부는?", choices: ["브리스길라와 아굴라", "아나니아와 삽비라", "안드로니고와 유니아", "루포와 그 어머니"], answerIndex: 0, explanation: "브리스길라와 아굴라는 바울과 같은 직업으로 고린도에서 동역했습니다.", reference: "사도행전 18:2~3" },
    { topic: "멜리데 섬", question: "바울이 탄 배가 파선하여 표류한 끝에 도착한 섬은?", choices: ["멜리데(몰타)", "구브로", "그레데", "밧모"], answerIndex: 0, explanation: "바울이 탄 배가 파선하여 멜리데(오늘날 몰타) 섬에 표류했습니다.", reference: "사도행전 28:1" },
    { topic: "야곱의 우물", question: "예수님이 사마리아 여인과 대화하신 우물은 누구의 우물?", choices: ["야곱의 우물", "아브라함의 우물", "이삭의 우물", "모세의 우물"], answerIndex: 0, explanation: "예수님은 야곱의 우물에서 사마리아 여인과 대화하셨습니다.", reference: "요한복음 4:6" },
    { topic: "베데스다", question: "예수님이 38년 된 병자를 고치신 예루살렘의 연못 이름은?", choices: ["베데스다", "실로암", "기혼", "헤스본"], answerIndex: 0, explanation: "베데스다 연못 가에서 38년 된 병자가 예수님께 고침을 받았습니다.", reference: "요한복음 5:2~9" },
    { topic: "실로암", question: "날 때부터 맹인 된 사람이 진흙을 바른 후 씻으라고 명령받은 못은?", choices: ["실로암", "베데스다", "기드론", "요단"], answerIndex: 0, explanation: "예수님이 맹인에게 실로암 못에 가서 씻으라 하셨고 눈이 열렸습니다.", reference: "요한복음 9:7" },
    { topic: "변화산 세 제자", question: "변화산 사건에서 예수님과 함께 올라간 세 제자는?", choices: ["베드로·야고보·요한", "베드로·안드레·빌립", "야고보·요한·도마", "베드로·요한·유다"], answerIndex: 0, explanation: "베드로, 야고보, 요한 세 제자가 변화산에 함께 올라갔습니다.", reference: "마태복음 17:1" },
  ],
  9: [
    { topic: "살렘", question: "멜기세덱이 왕으로 다스린 도성으로, \"평강의 왕\"이라는 뜻을 지닌 곳은?", choices: ["살렘", "소돔", "헤브론", "시온"], answerIndex: 0, explanation: "살렘은 '평강'의 뜻으로 멜기세덱이 다스린 도성입니다.", reference: "창세기 14:18, 히브리서 7:2" },
    { topic: "이스라엘과 브니엘", question: "야곱이 천사와 씨름한 후 받은 새 이름과 그 장소의 이름은?", choices: ["이스라엘 / 브니엘", "이스라엘 / 마하나임", "여수룬 / 벧엘", "이스라엘 / 숙곳"], answerIndex: 0, explanation: "야곱이 씨름 후 '이스라엘'이라는 새 이름을 받았고 그 장소를 '브니엘'이라 했습니다.", reference: "창세기 32:28, 32:30" },
    { topic: "흉패의 보석", question: "대제사장의 가슴에 다는 흉패에 박힌 보석의 수는?", choices: ["12개", "7개", "10개", "4개"], answerIndex: 0, explanation: "흉패에는 열두 지파를 상징하는 12개의 보석이 박혔습니다.", reference: "출애굽기 28:21" },
    { topic: "아사셀", question: "속죄일에 두 마리 염소 중, 광야로 보내지는 염소를 가리키는 말은?", choices: ["아사셀", "번제물", "화목제물", "속건제물"], answerIndex: 0, explanation: "아사셀 염소는 백성의 죄를 지고 광야로 보내지는 염소입니다.", reference: "레위기 16:8, 16:10" },
    { topic: "번제", question: "레위기의 다섯 가지 제사 중, 화재로 전부 태우는 제사는?", choices: ["번제", "소제", "화목제", "속건제"], answerIndex: 0, explanation: "번제는 제물 전부를 불로 태워 하나님께 드리는 헌신의 제사입니다.", reference: "레위기 1장" },
    { topic: "나실인 서원", question: "나실인의 서원 기간에 금지된 것이 아닌 것은?", choices: ["전쟁 참여", "포도주", "머리 깎기", "시체 접촉"], answerIndex: 0, explanation: "나실인 서원 금지 항목은 포도주·머리깎기·시체 접촉입니다. 전쟁 참여는 금지 항목이 아닙니다.", reference: "민수기 6:1~7" },
    { topic: "멜기세덱과 히브리서", question: "멜기세덱의 반차를 따른 영원한 제사장으로 예수님을 설명하는 책은?", choices: ["히브리서", "로마서", "갈라디아서", "골로새서"], answerIndex: 0, explanation: "히브리서는 예수님을 멜기세덱의 반차를 따른 영원한 대제사장으로 설명합니다.", reference: "히브리서 5:6, 7:17" },
    { topic: "둘째 아담", question: "로마서에서 바울이 \"둘째 아담\"으로 비유한 분은?", choices: ["예수 그리스도", "아브라함", "모세", "다윗"], answerIndex: 0, explanation: "바울은 예수 그리스도를 둘째 아담으로 비유하며 아담의 죄와 대비했습니다.", reference: "로마서 5:14~18" },
    { topic: "몽학선생", question: "갈라디아서에서 율법을 \"그리스도께로 인도하는 ○○○\"라 표현했다. 빈칸은?", choices: ["초등교사(몽학선생)", "중보자", "선지자", "파수꾼"], answerIndex: 0, explanation: "갈라디아서 3장 24절에서 율법을 '몽학선생'이라 표현했습니다.", reference: "갈라디아서 3:24" },
    { topic: "하나님의 형상", question: "골로새서에서 그리스도를 \"보이지 아니하는 하나님의 ○○\"이라 했다. 빈칸은?", choices: ["형상", "능력", "영광", "지혜"], answerIndex: 0, explanation: "골로새서 1장 15절에서 그리스도를 '보이지 아니하는 하나님의 형상'이라 했습니다.", reference: "골로새서 1:15" },
    { topic: "로고스", question: "요한복음 서두 \"태초에 ○○가 계시니라\"의 빈칸(헬라어 로고스)은?", choices: ["말씀", "빛", "생명", "진리"], answerIndex: 0, explanation: "요한복음 1장 1절 '태초에 말씀이 계시니라'입니다.", reference: "요한복음 1:1" },
    { topic: "생명의 떡", question: "예수님이 \"나는 ~이다\"(I AM)라고 하신 일곱 선언 중, 요한복음 6장의 것은?", choices: ["생명의 떡", "세상의 빛", "선한 목자", "부활이요 생명"], answerIndex: 0, explanation: "요한복음 6장 35절에서 예수님은 '나는 생명의 떡이라'고 선언하셨습니다.", reference: "요한복음 6:35" },
    { topic: "선한 목자", question: "\"선한 목자는 양들을 위하여 ○○을 버리거니와\"의 빈칸은?", choices: ["목숨", "양식", "우리", "들판"], answerIndex: 0, explanation: "요한복음 10장 11절 말씀입니다.", reference: "요한복음 10:11" },
    { topic: "팔복 - 긍휼", question: "산상수훈의 팔복 중 \"긍휼히 여기는 자는 ~\"의 약속은?", choices: ["긍휼히 여김을 받을 것임", "땅을 기업으로 받을 것임", "하나님을 볼 것임", "위로를 받을 것임"], answerIndex: 0, explanation: "긍휼히 여기는 자는 긍휼히 여김을 받을 것입니다.", reference: "마태복음 5:7" },
    { topic: "팔복 - 온유", question: "팔복에서 \"땅을 기업으로 받을 것임\"의 복을 받는 자는?", choices: ["온유한 자", "마음이 청결한 자", "애통하는 자", "의에 주린 자"], answerIndex: 0, explanation: "온유한 자가 땅을 기업으로 받을 것이라 하셨습니다.", reference: "마태복음 5:5" },
    { topic: "맨 나중에 멸망할 원수", question: "부활장으로 불리는 고린도전서 15장에서, \"맨 나중에 멸망 받을 원수\"는?", choices: ["사망", "죄", "사탄", "율법"], answerIndex: 0, explanation: "고린도전서 15장 26절에서 맨 나중에 멸망 받을 원수는 사망이라 했습니다.", reference: "고린도전서 15:26" },
    { topic: "구원의 투구", question: "에베소서 6장 \"전신갑주\"에서 \"구원의 ○○\"으로 표현된 것은?", choices: ["투구", "방패", "검", "신"], answerIndex: 0, explanation: "구원의 투구는 전신갑주의 일부입니다.", reference: "에베소서 6:17" },
    { topic: "성령의 검", question: "\"전신갑주\"에서 \"성령의 검\"으로 비유된 것은?", choices: ["하나님의 말씀", "믿음", "기도", "진리"], answerIndex: 0, explanation: "에베소서 6장 17절에서 성령의 검은 하나님의 말씀이라 했습니다.", reference: "에베소서 6:17" },
    { topic: "재림과 휴거", question: "데살로니가전서에서 강조한, 예수님의 재림과 관련된 사건은?", choices: ["죽은 자의 부활과 휴거", "천년왕국", "백보좌 심판", "새 예루살렘"], answerIndex: 0, explanation: "데살로니가전서 4장에서 재림 때 죽은 자가 먼저 부활하고 산 자가 들려 올라간다고 가르칩니다.", reference: "데살로니가전서 4:16~17" },
    { topic: "정결한 경건", question: "야고보서가 \"세상에서 정결한 경건\"으로 든 두 가지는?", choices: ["고아와 과부를 돌봄, 자기를 지킴", "금식과 기도", "십일조와 헌신", "전도와 봉사"], answerIndex: 0, explanation: "야고보서 1장 27절에 정결한 경건은 고아와 과부를 돌보고 자기를 지키는 것이라 했습니다.", reference: "야고보서 1:27" },
  ],
  10: [
    { topic: "팥죽과 장자권", question: "창세기에서 에서가 장자권을 판 대가로 받은 음식은?", choices: ["팥죽(붉은 죽)과 떡", "양고기", "무화과", "보리떡"], answerIndex: 0, explanation: "에서가 야곱에게 팥죽 한 그릇과 떡에 장자의 명분을 팔았습니다.", reference: "창세기 25:34" },
    { topic: "보디발의 직책", question: "요셉을 애굽에서 산 보디발의 직책은?", choices: ["친위대장", "술 맡은 관원장", "떡 굽는 관원장", "제사장"], answerIndex: 0, explanation: "보디발은 바로의 친위대장이었습니다.", reference: "창세기 39:1" },
    { topic: "장정의 수", question: "출애굽 시 이스라엘의 장정(20세 이상 남자)의 수로 민수기가 센 것은?", choices: ["약 60만 명", "약 12만 명", "약 100만 명", "약 30만 명"], answerIndex: 0, explanation: "민수기 1장 46절에 603,550명으로 기록되어 있습니다.", reference: "민수기 1:46" },
    { topic: "입다의 서원", question: "사사 입다가 경솔한 서원으로 인해 희생제물처럼 바치게 된 대상은?", choices: ["자신의 외동딸", "맏아들", "양 떼", "종"], answerIndex: 0, explanation: "입다의 외동딸이 전쟁 후 집에서 가장 먼저 나왔고 서원 때문에 바쳐졌습니다.", reference: "사사기 11:30~39" },
    { topic: "에벤에셀", question: "\"에벤에셀\"(여호와께서 여기까지 도우셨다)의 돌을 세운 사람은?", choices: ["사무엘", "여호수아", "다윗", "솔로몬"], answerIndex: 0, explanation: "사무엘이 블레셋 격파 후 에벤에셀 돌을 세워 기념했습니다.", reference: "사무엘상 7:12" },
    { topic: "브나야의 용맹", question: "다윗의 용사 중, 눈 오는 날 함정에 내려가 사자를 죽인 사람은?", choices: ["브나야", "아비새", "요압", "아사헬"], answerIndex: 0, explanation: "브나야가 눈 오는 날 함정에 내려가 사자를 죽이는 용맹을 보였습니다.", reference: "사무엘하 23:20" },
    { topic: "아히야 선지자", question: "솔로몬을 대적하여 도망쳤다가 후에 북왕국 왕이 된 사람을 도운 선지자는?", choices: ["아히야", "잇도", "스마야", "한나니"], answerIndex: 0, explanation: "아히야 선지자가 여로보암에게 옷을 열두 조각 내어 열 지파를 상징적으로 예언했습니다.", reference: "열왕기상 11:29~31" },
    { topic: "엘리사의 뼈", question: "엘리사가 죽은 후, 그의 뼈에 닿아 살아난 사건이 보여준 것은?", choices: ["죽은 시체가 되살아남", "나병이 나음", "눈이 뜨임", "도끼가 떠오름"], answerIndex: 0, explanation: "열왕기하 13장 21절에 사람의 시체가 엘리사의 뼈에 닿자 살아났습니다.", reference: "열왕기하 13:21" },
    { topic: "고멜", question: "호세아가 하나님의 명령으로 맞이한, 음란한 아내의 이름은?", choices: ["고멜", "디나", "오홀라", "발라"], answerIndex: 0, explanation: "호세아가 하나님의 명령으로 음란한 여인 고멜과 결혼했습니다.", reference: "호세아 1:3" },
    { topic: "아모스의 직업", question: "아모스의 직업(선지자가 되기 전)은?", choices: ["목자이자 뽕나무를 재배하는 자", "제사장", "서기관", "어부"], answerIndex: 0, explanation: "아모스 7장 14절에 아모스가 목자이며 뽕나무를 재배하는 자라고 소개합니다.", reference: "아모스 7:14" },
    { topic: "스룹바벨", question: "스가랴서에 등장하는, 대제사장 여호수아와 함께 성전 재건을 이끈 총독은?", choices: ["스룹바벨", "느헤미야", "에스라", "세스바살"], answerIndex: 0, explanation: "스룹바벨 총독과 대제사장 여호수아가 성전 재건을 이끌었습니다.", reference: "스가랴 4:6~9" },
    { topic: "마태 족보의 여인", question: "예수님의 족보(마태복음)에 등장하는 네 여인 중, 다말·라합·룻 다음 인물은?", choices: ["우리야의 아내(밧세바)", "사라", "리브가", "한나"], answerIndex: 0, explanation: "마태복음 1장 6절에서 우리야의 아내(밧세바)가 네 번째 여인으로 언급됩니다.", reference: "마태복음 1:6" },
    { topic: "삭개오", question: "누가복음에만 기록된, 세리장으로 뽕나무에 올라가 예수님을 본 사람은?", choices: ["삭개오", "레위", "바디매오", "나사로"], answerIndex: 0, explanation: "삭개오가 키가 작아 뽕나무에 올라가 예수님을 보려 했습니다.", reference: "누가복음 19:2~4" },
    { topic: "구레네 시몬", question: "예수님이 십자가에 달리실 때, 그 십자가를 억지로 진 구레네 사람은?", choices: ["시몬", "알렉산더", "루포", "글로바"], answerIndex: 0, explanation: "구레네 사람 시몬이 억지로 예수님의 십자가를 졌습니다.", reference: "마가복음 15:21" },
    { topic: "에디오피아 내시", question: "사도행전에서 빌립이 복음을 전하여 세례받은 에디오피아 내시가 읽던 성경은?", choices: ["이사야서", "시편", "다니엘서", "신명기"], answerIndex: 0, explanation: "에디오피아 내시가 이사야 53장을 읽다 빌립에게 복음을 들었습니다.", reference: "사도행전 8:28~33" },
    { topic: "엘루마의 형벌", question: "바울의 1차 전도여행 중, 박수(마술사) 엘루마가 일시적으로 당한 것은?", choices: ["눈이 멀게 됨", "말을 못 하게 됨", "즉사함", "귀가 막힘"], answerIndex: 0, explanation: "바울이 엘루마에게 선포하자 일시적으로 눈이 멀었습니다.", reference: "사도행전 13:11" },
    { topic: "셋째 하늘", question: "바울이 \"셋째 하늘\"에 이끌려 갔다고 간접적으로 표현한 서신은?", choices: ["고린도후서", "고린도전서", "로마서", "빌립보서"], answerIndex: 0, explanation: "고린도후서 12장 2절에 셋째 하늘에 이끌려 간 사람에 대한 기록이 있습니다.", reference: "고린도후서 12:2" },
    { topic: "일곱 교회 첫 번째", question: "요한계시록에서 일곱 교회에 보내는 편지의 순서상 첫 번째 교회는?", choices: ["에베소", "서머나", "버가모", "라오디게아"], answerIndex: 0, explanation: "요한계시록 2장 1절에서 에베소 교회에 보내는 편지가 첫 번째입니다.", reference: "요한계시록 2:1" },
    { topic: "짐승의 수", question: "요한계시록에서 \"짐승의 수\"로 기록된 숫자는?", choices: ["666", "144,000", "1,000", "12"], answerIndex: 0, explanation: "요한계시록 13장 18절에 짐승의 수는 666이라 기록되어 있습니다.", reference: "요한계시록 13:18" },
    { topic: "인침받은 수", question: "요한계시록에서 인침을 받은 이스라엘 자손의 수(각 지파 12,000명)는 총 몇 명?", choices: ["144,000명", "12,000명", "7,000명", "1,000,000명"], answerIndex: 0, explanation: "열두 지파 각 12,000명씩 총 144,000명이 인침을 받았습니다.", reference: "요한계시록 7:4" },
  ],
};

export const multipleChoiceQuestions: MultipleChoiceQuestion[] = Object.entries(levelData).flatMap(
  ([level, items]) =>
    items.map((item, index) => ({
      id: questionId(Number(level), "mc", index),
      level: Number(level),
      type: "multiple_choice" as const,
      category: item.topic,
      difficulty: getDifficulty(Number(level)),
      question: item.question,
      payload: { choices: item.choices as [string, string, string, string] },
      answer: { index: item.answerIndex },
      explanation: item.explanation,
      reference: item.reference,
    })),
);
