import type { TrueFalseQuestion } from "../bibleQuiz";
import { getDifficulty, questionId } from "./shared";

type TrueFalseItem = {
  category: string;
  statement: string;
  answer: boolean;
  explanation: string;
  reference: string;
};

const levelData: Record<number, TrueFalseItem[]> = {
  1: [
    {
      category: "천지창조",
      statement: "하나님은 엿새 동안 천지를 창조하시고 일곱째 날에 안식하셨다.",
      answer: true,
      explanation: "하나님은 엿새 동안 만물을 지으시고 일곱째 날에 안식하셨다.",
      reference: "창세기 2:2",
    },
    {
      category: "에덴동산",
      statement: "아담의 갈빗대로 하와를 만드셨다.",
      answer: true,
      explanation: "하나님은 아담의 갈빗대 하나로 여자를 만드셨다.",
      reference: "창세기 2:21-22",
    },
    {
      category: "선악과",
      statement: "하와는 뱀의 유혹을 받아 선악을 알게 하는 나무의 열매를 먹었다.",
      answer: true,
      explanation: "하와는 뱀의 꾐에 빠져 금지된 열매를 따 먹었다.",
      reference: "창세기 3:6",
    },
    {
      category: "가인과 아벨",
      statement: "가인은 동생 아벨을 시기하여 죽였다.",
      answer: true,
      explanation: "가인은 아벨을 시기하여 들에서 그를 쳐죽였다.",
      reference: "창세기 4:8",
    },
    {
      category: "노아의 방주",
      statement: "노아는 사십 일 밤낮 동안 방주를 만들었다.",
      answer: false,
      explanation: "방주 완성 후 비가 사십 주야 내린 것이며, 방주 건조 자체는 오랜 기간에 걸친 일이었다.",
      reference: "창세기 7:12",
    },
    {
      category: "바벨탑",
      statement: "사람들이 바벨탑을 쌓자 하나님은 그들의 언어를 혼잡하게 하셨다.",
      answer: true,
      explanation: "하나님은 바벨에서 사람들의 언어를 혼잡하게 하여 흩으셨다.",
      reference: "창세기 11:9",
    },
    {
      category: "아브라함의 부르심",
      statement: "하나님은 아브라함에게 애굽 땅을 떠나라고 명하셨다.",
      answer: false,
      explanation: "하나님은 아브라함에게 본토 갈대아 우르(하란)를 떠나라고 명하셨다.",
      reference: "창세기 12:1",
    },
    {
      category: "이삭의 출생",
      statement: "사라는 백 세에 이삭을 낳은 아브라함의 아내이다.",
      answer: false,
      explanation: "아브라함이 백 세에 이삭을 낳았고, 사라는 그때 구십 세였다.",
      reference: "창세기 17:17",
    },
    {
      category: "야곱과 에서",
      statement: "야곱은 팥죽 한 그릇으로 형 에서에게서 장자의 명분을 샀다.",
      answer: true,
      explanation: "에서는 팥죽 한 그릇에 장자의 명분을 야곱에게 팔았다.",
      reference: "창세기 25:33-34",
    },
    {
      category: "요셉",
      statement: "요셉은 형들에 의해 애굽으로 가는 상인들에게 은 이십 개에 팔렸다.",
      answer: true,
      explanation: "요셉은 형들에 의해 은 이십 개에 이스마엘 사람들에게 팔렸다.",
      reference: "창세기 37:28",
    },
  ],
  2: [
    {
      category: "모세의 출생",
      statement: "모세는 갈대 상자에 담겨 나일 강에 띄워졌다.",
      answer: true,
      explanation: "모세의 어머니는 갈대 상자에 그를 담아 나일 강가 갈대 사이에 두었다.",
      reference: "출애굽기 2:3",
    },
    {
      category: "불붙은 떨기나무",
      statement: "하나님은 시내산의 불붙은 떨기나무 가운데서 모세를 부르셨다.",
      answer: false,
      explanation: "하나님은 호렙산의 불붙은 떨기나무 가운데서 모세를 부르셨다.",
      reference: "출애굽기 3:1-2",
    },
    {
      category: "열 가지 재앙",
      statement: "애굽에 내린 마지막 재앙은 장자의 죽음이었다.",
      answer: true,
      explanation: "열 번째 재앙으로 애굽의 모든 장자가 죽었다.",
      reference: "출애굽기 12:29",
    },
    {
      category: "유월절",
      statement: "이스라엘 백성은 문설주에 양의 피를 발라 장자의 죽음을 면했다.",
      answer: true,
      explanation: "어린 양의 피를 문 좌우 설주와 인방에 바른 집은 재앙을 넘겼다.",
      reference: "출애굽기 12:7",
    },
    {
      category: "홍해를 건넘",
      statement: "모세가 지팡이를 들자 요단 강이 갈라져 백성이 건넜다.",
      answer: false,
      explanation: "모세가 손을 내밀자 홍해가 갈라져 이스라엘 백성이 마른 땅으로 건넜다.",
      reference: "출애굽기 14:21-22",
    },
    {
      category: "만나와 메추라기",
      statement: "광야에서 하나님은 하늘에서 만나를 내려 백성을 먹이셨다.",
      answer: true,
      explanation: "하나님은 광야에서 아침마다 만나를 내려 이스라엘을 먹이셨다.",
      reference: "출애굽기 16:14-15",
    },
    {
      category: "십계명",
      statement: "모세는 시내산에서 하나님께 십계명을 받았다.",
      answer: true,
      explanation: "하나님은 시내산에서 모세에게 두 돌판에 새긴 십계명을 주셨다.",
      reference: "출애굽기 20:1",
    },
    {
      category: "금송아지",
      statement: "아론은 백성의 요구로 금송아지를 만들었다.",
      answer: true,
      explanation: "아론은 백성이 모은 금 고리로 금송아지를 만들었다.",
      reference: "출애굽기 32:4",
    },
    {
      category: "열두 정탐꾼",
      statement: "가나안을 정탐한 열두 명 중 여호수아와 갈렙만 긍정적으로 보고했다.",
      answer: true,
      explanation: "여호수아와 갈렙만이 가나안 정복을 확신하는 보고를 했다.",
      reference: "민수기 14:6-9",
    },
    {
      category: "놋뱀",
      statement: "광야에서 백성이 불뱀에 물렸을 때 모세는 놋뱀을 장대에 매달았다.",
      answer: true,
      explanation: "모세가 놋뱀을 장대에 달자 그것을 쳐다본 자는 살았다.",
      reference: "민수기 21:9",
    },
  ],
  3: [
    {
      category: "사무엘의 부르심",
      statement: "어린 사무엘은 성전에서 자다가 하나님의 부르심을 들었다.",
      answer: true,
      explanation: "하나님은 잠자던 어린 사무엘을 여러 번 부르셨다.",
      reference: "사무엘상 3:4",
    },
    {
      category: "사울의 기름부음",
      statement: "사무엘은 사울에게 기름을 부어 이스라엘의 첫 왕으로 세웠다.",
      answer: true,
      explanation: "사무엘은 사울에게 기름을 부어 이스라엘의 왕으로 세웠다.",
      reference: "사무엘상 10:1",
    },
    {
      category: "다윗과 골리앗",
      statement: "다윗은 물맷돌로 블레셋 장수 골리앗을 쓰러뜨렸다.",
      answer: true,
      explanation: "다윗은 물매로 던진 돌로 골리앗의 이마를 쳐서 죽였다.",
      reference: "사무엘상 17:49",
    },
    {
      category: "다윗과 요나단",
      statement: "사울의 아들 압살롬은 다윗과 깊은 우정을 맺었다.",
      answer: false,
      explanation: "다윗과 언약을 맺어 깊은 우정을 나눈 사람은 사울의 아들 요나단이다.",
      reference: "사무엘상 18:1-3",
    },
    {
      category: "다윗과 밧세바",
      statement: "다윗은 밧세바의 남편 우리아를 전쟁터에서 죽게 했다.",
      answer: true,
      explanation: "다윗은 우리아를 격전지에 두어 죽게 만들었다.",
      reference: "사무엘하 11:15-17",
    },
    {
      category: "나단의 책망",
      statement: "선지자 나단은 비유로 다윗의 죄를 책망했다.",
      answer: true,
      explanation: "나단은 부자와 가난한 자의 비유로 다윗의 죄를 지적했다.",
      reference: "사무엘하 12:1-7",
    },
    {
      category: "압살롬의 반역",
      statement: "다윗의 아들 압살롬은 아버지에게 반역을 일으켰다.",
      answer: true,
      explanation: "압살롬은 다윗을 대적하여 반역을 일으켰다.",
      reference: "사무엘하 15:10",
    },
    {
      category: "솔로몬의 즉위",
      statement: "다윗의 뒤를 이어 왕이 된 사람은 아도니야였다.",
      answer: false,
      explanation: "다윗의 뒤를 이어 이스라엘의 왕이 된 사람은 솔로몬이다.",
      reference: "열왕기상 1:39",
    },
    {
      category: "솔로몬의 지혜",
      statement: "솔로몬은 두 여인이 한 아이를 두고 다툴 때 칼로 나누라며 친어머니를 가렸다.",
      answer: true,
      explanation: "솔로몬은 아이를 둘로 나누라는 명령으로 참어머니를 분별했다.",
      reference: "열왕기상 3:25-27",
    },
    {
      category: "성전 건축",
      statement: "솔로몬은 예루살렘에 여호와의 성전을 건축했다.",
      answer: true,
      explanation: "솔로몬은 예루살렘에 여호와를 위한 성전을 지었다.",
      reference: "열왕기상 6:14",
    },
  ],
  4: [
    {
      category: "예수님의 탄생",
      statement: "예수님은 베들레헴에서 태어나 구유에 뉘어졌다.",
      answer: true,
      explanation: "예수님은 베들레헴에서 나셔서 구유에 뉘어지셨다.",
      reference: "누가복음 2:7",
    },
    {
      category: "동방박사",
      statement: "동방에서 온 박사들은 별을 따라와 아기 예수께 경배했다.",
      answer: true,
      explanation: "동방박사들은 별을 보고 찾아와 아기 예수께 경배하고 예물을 드렸다.",
      reference: "마태복음 2:11",
    },
    {
      category: "세례 요한",
      statement: "예수님은 베드로에게 요단 강에서 세례를 받으셨다.",
      answer: false,
      explanation: "예수님은 세례 요한에게 요단 강에서 세례를 받으셨다.",
      reference: "마태복음 3:13",
    },
    {
      category: "광야의 시험",
      statement: "예수님은 광야에서 사십 일 동안 마귀에게 시험을 받으셨다.",
      answer: true,
      explanation: "예수님은 광야에서 사십 일을 금식하시며 마귀의 시험을 받으셨다.",
      reference: "마태복음 4:1-2",
    },
    {
      category: "열두 제자",
      statement: "예수님은 일흔 명의 제자를 사도로 부르셨다.",
      answer: false,
      explanation: "예수님은 열두 제자를 사도로 택하여 세우셨다.",
      reference: "누가복음 6:13",
    },
    {
      category: "변화산",
      statement: "변화산에서 예수님과 함께 모세와 엘리야가 나타났다.",
      answer: true,
      explanation: "변화산에서 모세와 엘리야가 예수님과 더불어 말하는 것이 나타났다.",
      reference: "마태복음 17:3",
    },
    {
      category: "최후의 만찬",
      statement: "예수님은 제자들과 함께 마지막 유월절 만찬을 나누셨다.",
      answer: true,
      explanation: "예수님은 잡히시기 전 제자들과 유월절 만찬을 나누며 떡과 잔을 주셨다.",
      reference: "마태복음 26:26-28",
    },
    {
      category: "베드로의 부인",
      statement: "베드로는 닭 울기 전에 예수님을 세 번 부인했다.",
      answer: true,
      explanation: "베드로는 닭이 울기 전 예수님을 세 번 모른다고 했다.",
      reference: "마태복음 26:75",
    },
    {
      category: "십자가",
      statement: "예수님은 골고다라 하는 곳에서 십자가에 못 박히셨다.",
      answer: true,
      explanation: "예수님은 해골의 곳이라 하는 골고다에서 십자가에 달리셨다.",
      reference: "마태복음 27:33-35",
    },
    {
      category: "부활",
      statement: "예수님은 죽으신 지 사흘째 되는 날 다시 살아나셨다.",
      answer: true,
      explanation: "예수님은 안식 후 첫날 곧 사흘 만에 부활하셨다.",
      reference: "마태복음 28:6",
    },
  ],
  5: [
    {
      category: "씨 뿌리는 비유",
      statement: "씨 뿌리는 비유에서 좋은 땅에 떨어진 씨는 결실을 맺었다.",
      answer: true,
      explanation: "좋은 땅에 떨어진 씨는 삼십 배, 육십 배, 백 배의 결실을 맺었다.",
      reference: "마가복음 4:8",
    },
    {
      category: "선한 사마리아인",
      statement: "선한 사마리아인 비유에서 강도 만난 자를 도운 이는 제사장이었다.",
      answer: false,
      explanation: "제사장과 레위인은 그냥 지나갔고, 강도 만난 자를 도운 이는 사마리아인이었다.",
      reference: "누가복음 10:33",
    },
    {
      category: "탕자의 비유",
      statement: "탕자의 비유에서 아버지는 돌아온 작은 아들을 기쁨으로 맞이했다.",
      answer: true,
      explanation: "아버지는 돌아온 둘째 아들을 측은히 여겨 달려가 안고 잔치를 베풀었다.",
      reference: "누가복음 15:20",
    },
    {
      category: "물로 포도주",
      statement: "예수님은 가나의 혼인 잔치에서 물로 포도주를 만드셨다.",
      answer: true,
      explanation: "예수님은 가나 혼인 잔치에서 물을 포도주로 변하게 하셨다.",
      reference: "요한복음 2:9",
    },
    {
      category: "오병이어",
      statement: "예수님은 떡 일곱 개와 물고기 두 마리로 오천 명을 먹이셨다.",
      answer: false,
      explanation: "예수님은 떡 다섯 개와 물고기 두 마리로 오천 명을 먹이셨다.",
      reference: "요한복음 6:9-11",
    },
    {
      category: "물 위를 걸으심",
      statement: "예수님은 갈릴리 바다 위를 걸어 제자들에게 가셨다.",
      answer: true,
      explanation: "예수님은 바다 위로 걸어서 배에 있던 제자들에게 가셨다.",
      reference: "마태복음 14:25",
    },
    {
      category: "풍랑을 잔잔케 하심",
      statement: "예수님은 풍랑을 꾸짖어 바다를 잔잔하게 하셨다.",
      answer: true,
      explanation: "예수님은 바람과 바다를 꾸짖으시니 아주 잔잔해졌다.",
      reference: "마가복음 4:39",
    },
    {
      category: "나사로의 부활",
      statement: "예수님은 죽은 지 나흘 된 나사로를 무덤에서 살리셨다.",
      answer: true,
      explanation: "예수님은 무덤에 나흘 있던 나사로를 불러내어 살리셨다.",
      reference: "요한복음 11:43-44",
    },
    {
      category: "맹인을 고치심",
      statement: "예수님은 진흙을 이겨 날 때부터 맹인 된 자의 눈에 발라 고치셨다.",
      answer: true,
      explanation: "예수님은 침으로 진흙을 만들어 맹인의 눈에 바르고 실로암에서 씻게 해 고치셨다.",
      reference: "요한복음 9:6-7",
    },
    {
      category: "잃은 양의 비유",
      statement: "잃은 양의 비유에서 목자는 아흔아홉 마리를 두고 잃은 한 마리를 찾으러 갔다.",
      answer: true,
      explanation: "목자는 아흔아홉 마리를 두고 잃은 양 한 마리를 찾을 때까지 찾아다닌다.",
      reference: "누가복음 15:4",
    },
  ],
  6: [
    {
      category: "성령 강림",
      statement: "오순절에 성령이 불의 혀같이 갈라져 제자들에게 임했다.",
      answer: true,
      explanation: "오순절 날 불의 혀처럼 갈라지는 것이 제자들 위에 임했다.",
      reference: "사도행전 2:3",
    },
    {
      category: "베드로의 설교",
      statement: "오순절 베드로의 설교로 약 삼천 명이 세례를 받았다.",
      answer: true,
      explanation: "베드로의 설교를 받은 사람이 세례를 받으니 그날 삼천 명쯤 더해졌다.",
      reference: "사도행전 2:41",
    },
    {
      category: "스데반의 순교",
      statement: "스데반은 초대교회 최초의 순교자로 돌에 맞아 죽었다.",
      answer: true,
      explanation: "스데반은 사람들에게 돌에 맞아 순교한 최초의 순교자이다.",
      reference: "사도행전 7:59-60",
    },
    {
      category: "사울의 회심",
      statement: "사울은 다메섹 도상에서 빛을 보고 예수님을 만나 회심했다.",
      answer: true,
      explanation: "사울은 다메섹으로 가는 길에서 부활하신 예수님을 만나 회심했다.",
      reference: "사도행전 9:3-6",
    },
    {
      category: "고넬료",
      statement: "베드로는 사마리아 군대 백부장 고넬료에게 복음을 전했다.",
      answer: false,
      explanation: "고넬료는 가이사랴에 주둔한 이달리야 부대의 백부장이었다.",
      reference: "사도행전 10:1",
    },
    {
      category: "베드로의 옥문",
      statement: "베드로가 옥에 갇혔을 때 천사가 그를 인도하여 풀어주었다.",
      answer: true,
      explanation: "주의 사자가 옥에 갇힌 베드로를 깨워 쇠사슬을 벗기고 인도해 나왔다.",
      reference: "사도행전 12:7",
    },
    {
      category: "안디옥 교회",
      statement: "제자들이 그리스도인이라 불린 것은 예루살렘에서 비롯되었다.",
      answer: false,
      explanation: "제자들이 그리스도인이라 일컬음을 받은 것은 안디옥에서 처음이었다.",
      reference: "사도행전 11:26",
    },
    {
      category: "빌립과 내시",
      statement: "빌립은 마차에서 이사야서를 읽던 에디오피아 내시에게 복음을 전했다.",
      answer: true,
      explanation: "빌립은 이사야서를 읽던 에디오피아 내시에게 예수를 전하고 세례를 주었다.",
      reference: "사도행전 8:35-38",
    },
    {
      category: "바울과 실라",
      statement: "바울과 실라는 빌립보 감옥에서 찬송할 때 지진으로 옥문이 열렸다.",
      answer: true,
      explanation: "바울과 실라가 기도하며 찬송할 때 큰 지진으로 옥문이 다 열렸다.",
      reference: "사도행전 16:25-26",
    },
    {
      category: "예루살렘 공의회",
      statement: "예루살렘 공의회는 이방인 신자에게 할례를 강요하지 않기로 결정했다.",
      answer: true,
      explanation: "예루살렘 공의회는 이방인에게 할례 등의 짐을 지우지 않기로 결정했다.",
      reference: "사도행전 15:19-20",
    },
  ],
  7: [
    {
      category: "호세아",
      statement: "호세아는 음란한 여인 고멜을 아내로 맞이하라는 명을 받았다.",
      answer: true,
      explanation: "하나님은 호세아에게 음란한 여인 고멜을 아내로 취하라 하셨다.",
      reference: "호세아 1:2-3",
    },
    {
      category: "요엘",
      statement: "요엘은 메뚜기 재앙과 여호와의 날에 대해 예언했다.",
      answer: true,
      explanation: "요엘은 메뚜기 재앙을 통해 회개를 촉구하고 여호와의 날을 예언했다.",
      reference: "요엘 1:4",
    },
    {
      category: "아모스",
      statement: "목자 출신 아모스는 공의를 물 같이 흐르게 하라고 외쳤다.",
      answer: true,
      explanation: "아모스는 오직 정의를 물 같이, 공의를 마르지 않는 강 같이 흐르게 하라고 했다.",
      reference: "아모스 5:24",
    },
    {
      category: "요나",
      statement: "요나는 니느웨로 가라는 명을 피해 다소로 가는 배를 탔다.",
      answer: false,
      explanation: "요나는 니느웨로 가라는 명을 피해 다시스로 가는 배를 탔다.",
      reference: "요나 1:3",
    },
    {
      category: "요나와 큰 물고기",
      statement: "요나는 큰 물고기 배 속에서 삼 일 밤낮을 있었다.",
      answer: true,
      explanation: "요나는 큰 물고기 배 속에서 삼 일 삼 야를 지냈다.",
      reference: "요나 1:17",
    },
    {
      category: "미가",
      statement: "미가는 메시아가 나사렛에서 나리라고 예언했다.",
      answer: false,
      explanation: "미가는 다스릴 자가 베들레헴 에브라다에서 나리라고 예언했다.",
      reference: "미가 5:2",
    },
    {
      category: "하박국",
      statement: "하박국은 의인은 그 믿음으로 말미암아 살리라고 기록했다.",
      answer: true,
      explanation: "하박국은 오직 의인은 그의 믿음으로 말미암아 살리라고 했다.",
      reference: "하박국 2:4",
    },
    {
      category: "스가랴",
      statement: "스가랴는 왕이 나귀를 타고 예루살렘에 임할 것을 예언했다.",
      answer: true,
      explanation: "스가랴는 왕이 겸손하여 나귀를 타고 시온에 임할 것을 예언했다.",
      reference: "스가랴 9:9",
    },
    {
      category: "말라기",
      statement: "말라기는 백성에게 온전한 십일조를 창고에 들이라고 촉구했다.",
      answer: true,
      explanation: "말라기는 온전한 십일조를 창고에 들여 하나님을 시험해 보라고 했다.",
      reference: "말라기 3:10",
    },
    {
      category: "오바댜",
      statement: "오바댜는 형제 유다를 배반한 에돔의 멸망을 선언했다.",
      answer: true,
      explanation: "오바댜는 형제 야곱을 학대한 에돔에 대한 심판을 선언했다.",
      reference: "오바댜 1:10",
    },
  ],
  8: [
    {
      category: "여리고 성",
      statement: "이스라엘은 여리고 성을 이레 동안 돌아 무너뜨렸다.",
      answer: true,
      explanation: "이스라엘은 칠 일째 성을 일곱 번 돌고 외치니 여리고 성벽이 무너졌다.",
      reference: "여호수아 6:20",
    },
    {
      category: "기생 라합",
      statement: "기생 라합은 여리고에 온 정탐꾼들을 숨겨주었다.",
      answer: true,
      explanation: "라합은 여호수아가 보낸 정탐꾼들을 자기 집에 숨겨 보호했다.",
      reference: "여호수아 2:4",
    },
    {
      category: "기드온",
      statement: "기드온은 삼백 명의 군사로 미디안을 물리쳤다.",
      answer: true,
      explanation: "기드온은 삼백 명으로 미디안 대군을 물리쳤다.",
      reference: "사사기 7:7",
    },
    {
      category: "삼손",
      statement: "삼손의 힘의 비밀은 그의 머리카락에 있었다.",
      answer: true,
      explanation: "삼손의 힘은 깎지 않은 머리카락에 있었고, 들릴라가 이를 알아냈다.",
      reference: "사사기 16:17",
    },
    {
      category: "드보라",
      statement: "사사 드보라는 바락과 함께 시스라 군대를 물리쳤다.",
      answer: true,
      explanation: "여선지자이자 사사인 드보라는 바락과 함께 시스라의 군대를 이겼다.",
      reference: "사사기 4:14-15",
    },
    {
      category: "룻",
      statement: "모압 여인 룻은 시어머니 나오미를 떠나 고향에 머물렀다.",
      answer: false,
      explanation: "룻은 시어머니 나오미를 떠나지 않고 따라가겠다고 했다.",
      reference: "룻기 1:16",
    },
    {
      category: "보아스",
      statement: "보아스는 룻을 아내로 맞아 오벳을 낳았고 그는 다윗의 조부가 되었다.",
      answer: true,
      explanation: "보아스와 룻 사이에서 난 오벳은 이새의 아버지요 다윗의 조부이다.",
      reference: "룻기 4:17",
    },
    {
      category: "엘리야",
      statement: "엘리야는 갈멜산에서 바알 선지자들과 대결하여 승리했다.",
      answer: true,
      explanation: "엘리야는 갈멜산에서 하늘의 불로 응답받아 바알 선지자들을 이겼다.",
      reference: "열왕기상 18:38-39",
    },
    {
      category: "나아만",
      statement: "아람 장군 나아만은 요단 강에 일곱 번 몸을 씻고 나병이 나았다.",
      answer: true,
      explanation: "나아만은 엘리사의 말대로 요단 강에 일곱 번 몸을 잠그자 나병이 나았다.",
      reference: "열왕기하 5:14",
    },
    {
      category: "느헤미야",
      statement: "느헤미야는 무너진 예루살렘 성벽을 오십이 일 만에 재건했다.",
      answer: true,
      explanation: "느헤미야의 지휘로 예루살렘 성벽이 오십이 일 만에 완성되었다.",
      reference: "느헤미야 6:15",
    },
  ],
  9: [
    {
      category: "이신칭의",
      statement: "로마서는 사람이 율법의 행위가 아니라 믿음으로 의롭게 된다고 가르친다.",
      answer: true,
      explanation: "사람이 의롭다 하심을 얻는 것은 율법의 행위가 아니라 믿음으로 된다.",
      reference: "로마서 3:28",
    },
    {
      category: "사랑장",
      statement: "고린도전서 13장은 믿음, 소망, 사랑 중 그중에 제일은 사랑이라고 한다.",
      answer: true,
      explanation: "믿음, 소망, 사랑 이 세 가지는 항상 있으며 그중의 제일은 사랑이다.",
      reference: "고린도전서 13:13",
    },
    {
      category: "성령의 열매",
      statement: "갈라디아서가 말하는 성령의 열매는 사랑, 희락, 화평 등 아홉 가지이다.",
      answer: true,
      explanation: "성령의 열매는 사랑, 희락, 화평, 오래 참음 등 아홉 가지로 열거된다.",
      reference: "갈라디아서 5:22-23",
    },
    {
      category: "구원은 은혜로",
      statement: "에베소서는 구원이 행위에서 난 것이라 자랑할 수 있다고 가르친다.",
      answer: false,
      explanation: "구원은 행위에서 난 것이 아니요 하나님의 선물이니 아무도 자랑하지 못한다.",
      reference: "에베소서 2:8-9",
    },
    {
      category: "그리스도의 겸손",
      statement: "빌립보서는 그리스도께서 자기를 비워 종의 형체를 가지셨다고 한다.",
      answer: true,
      explanation: "그리스도께서 자기를 비워 종의 형체를 가지고 사람과 같이 되셨다.",
      reference: "빌립보서 2:7",
    },
    {
      category: "믿음의 정의",
      statement: "히브리서는 믿음을 바라는 것들의 실상이요 보이지 않는 것들의 증거라 한다.",
      answer: true,
      explanation: "믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거이다.",
      reference: "히브리서 11:1",
    },
    {
      category: "행함과 믿음",
      statement: "야고보서는 행함이 없는 믿음은 그 자체가 죽은 것이라고 한다.",
      answer: true,
      explanation: "행함이 없는 믿음은 그 자체가 죽은 것이다.",
      reference: "야고보서 2:17",
    },
    {
      category: "산 소망",
      statement: "베드로전서는 산 소망이 모세의 율법으로 났다고 가르친다.",
      answer: false,
      explanation: "산 소망은 예수 그리스도를 죽은 자 가운데서 부활하게 하심으로 났다.",
      reference: "베드로전서 1:3",
    },
    {
      category: "하나님은 사랑",
      statement: "요한일서는 하나님은 사랑이시라고 선언한다.",
      answer: true,
      explanation: "요한일서는 하나님은 사랑이시며 사랑 안에 거하는 자가 하나님 안에 거한다고 한다.",
      reference: "요한일서 4:8",
    },
    {
      category: "유다서",
      statement: "유다서는 믿음의 도를 위하여 힘써 싸우라고 권면한다.",
      answer: true,
      explanation: "유다서는 단번에 주신 믿음의 도를 위하여 힘써 싸우라고 권면한다.",
      reference: "유다서 1:3",
    },
  ],
  10: [
    {
      category: "기록자",
      statement: "요한계시록은 밧모 섬에 있던 사도 요한이 받은 계시이다.",
      answer: true,
      explanation: "요한은 밧모라 하는 섬에 있을 때 예수 그리스도의 계시를 받았다.",
      reference: "요한계시록 1:9",
    },
    {
      category: "일곱 교회",
      statement: "요한계시록은 아시아의 일곱 교회에 보내는 편지로 시작한다.",
      answer: true,
      explanation: "요한계시록은 에베소, 서머나 등 아시아의 일곱 교회에 보내는 말씀으로 시작한다.",
      reference: "요한계시록 1:11",
    },
    {
      category: "라오디게아 교회",
      statement: "라오디게아 교회는 뜨겁지도 차지도 않은 미지근한 교회로 책망받았다.",
      answer: true,
      explanation: "라오디게아 교회는 차지도 뜨겁지도 않고 미지근하여 책망을 받았다.",
      reference: "요한계시록 3:16",
    },
    {
      category: "보좌 환상",
      statement: "요한은 하늘 보좌 둘레에 스물네 장로가 앉아 있는 것을 보았다.",
      answer: true,
      explanation: "요한은 하늘 보좌를 둘러 이십사 보좌에 이십사 장로가 앉은 것을 보았다.",
      reference: "요한계시록 4:4",
    },
    {
      category: "어린 양",
      statement: "일곱 인으로 봉한 두루마리를 펴기에 합당한 이는 사자라 하는 천사였다.",
      answer: false,
      explanation: "두루마리를 펴기에 합당한 이는 죽임을 당한 것 같은 어린 양(예수 그리스도)이었다.",
      reference: "요한계시록 5:6-9",
    },
    {
      category: "일곱 나팔",
      statement: "요한계시록에는 일곱 천사가 일곱 나팔을 부는 심판이 나온다.",
      answer: true,
      explanation: "일곱 나팔을 가진 일곱 천사가 차례로 나팔을 불어 심판이 임한다.",
      reference: "요한계시록 8:6",
    },
    {
      category: "짐승의 표",
      statement: "요한계시록에서 짐승의 수는 칠백칠십칠로 기록되어 있다.",
      answer: false,
      explanation: "짐승의 수는 사람의 수니 곧 육백육십육이라고 기록되어 있다.",
      reference: "요한계시록 13:18",
    },
    {
      category: "용과의 싸움",
      statement: "천사장 미가엘과 그의 사자들이 용과 싸워 하늘에서 쫓아냈다.",
      answer: true,
      explanation: "미가엘과 그의 사자들이 용 곧 옛 뱀과 싸워 하늘에서 내쫓았다.",
      reference: "요한계시록 12:7-9",
    },
    {
      category: "새 하늘과 새 땅",
      statement: "요한은 새 하늘과 새 땅, 그리고 새 예루살렘이 내려오는 것을 보았다.",
      answer: true,
      explanation: "요한은 새 하늘과 새 땅을 보았고 거룩한 성 새 예루살렘이 내려오는 것을 보았다.",
      reference: "요한계시록 21:1-2",
    },
    {
      category: "생명수 강",
      statement: "새 예루살렘에는 보좌로부터 흘러나오는 생명수의 강이 있다.",
      answer: true,
      explanation: "수정같이 맑은 생명수의 강이 하나님과 어린 양의 보좌로부터 흘러나온다.",
      reference: "요한계시록 22:1",
    },
  ],
};

export const trueFalseQuestions: TrueFalseQuestion[] = Object.entries(levelData).flatMap(([level, items]) =>
  items.map((item, index) => ({
    id: questionId(Number(level), "tf", index),
    level: Number(level),
    type: "true_false",
    category: item.category,
    difficulty: getDifficulty(Number(level)),
    question: `${item.statement} - OX`,
    payload: {},
    answer: { value: item.answer },
    explanation: item.explanation,
    reference: item.reference,
  })),
);
